### ISSUE TITLE
How to obtain smpl translation parameters?

### ISSUE THREAD

**Issue by jyuntins** [shubham-goel/4D-Humans#100]
Hi, thank you for your great work. When I run the tracking demo, I found the smpl parameters only contains global orientation, shapes and poses. I wonder Is there a simple way to get the smpl translation?

**Comment by geopavlakos** [comment]
It's the [pred_cam_t_full](https://github.com/shubham-goel/4D-Humans/blob/124e8b2dc041fdd7e02f879ce851952cb810636b/demo.py#L94) variable.

**Comment by jyuntins** [comment]
Thanks for the quick reply. I do can get pred_cam_t_full when I run demo.py. However, If I run track.py which contains the PHALP tracker, the cam_translation is not saved in the smpl parameters.

**Comment by geopavlakos** [comment]
It's stored in the `camera` key. :)

**Comment by jyuntins** [comment]
I tried to use the camera key as the translation and render the smpl in world coordinate. The results look like this. I also try to store the mesh used in the renderer/render_rgba_multiple. It generates the same result. I guess this method can predict the shape and pose very well, while for the depth it can't generate good result due to scale ambiguity? (in my test image)
![Screenshot from 2024-04-03 08-28-14](https://github.com/shubham-goel/4D-Humans/assets/67471291/cd91961c-8d78-4f5e-8115-14c175c54c9d)
and this is the test image.
![00001](https://github.com/shubham-goel/4D-Humans/assets/67471291/81235b74-1f5a-44c5-9570-72c52d61c71a)

**Comment by geopavlakos** [comment]
Please take a look at this issue: https://github.com/shubham-goel/4D-Humans/issues/16
