### ISSUE TITLE
mocap data

### ISSUE THREAD

**Issue by luoxue-star** [shubham-goel/4D-Humans#106]
May I ask how the mocap.npz file was obtained? Is it done by calculating the average of all poses and shapes?

**Comment by geopavlakos** [comment]
Th `cmu_mocap.npz` file includes the CMU MoCap data in SMPL format, generated by [MoSh](https://ps.is.mpg.de/publications/loper-sigasia-2014) and released by the [original HMR work](https://github.com/akanazawa/hmr).
