### ISSUE TITLE
About the dataset annotations

### ISSUE THREAD

**Issue by 3huo** [shubham-goel/4D-Humans#107]
Hi~
     I noticed that the annotations about smpl params is provided, but if I want to show the mesh projected on the original image, I think still need the focal length and principal and cam_trans. 
    In the insta-variety dataset, I noticed that {'center', 'scale', 'fitting cam trans'} is provided, and I set f = 5000*scale*200/256, but it couldn't get a correct rendering.  so I don't know how to fix it,  could u please help me about it?

**Comment by wengzejia1** [comment]
Hi, have you solved the problem. Can you share your experience visualizing the projection results of insta-variety dataset.
