### ISSUE TITLE
How can I use the detection result to calculate the limb length？

### ISSUE THREAD

**Issue by TZYSJTU** [shubham-goel/4D-Humans#109]
Hello，I just heard this wonderful work. But I do not have enough time to see the full code. I wanna know if I want to measure the body limb length of the smpl, where  and which line can I refer to? Thanks very much.

**Comment by geopavlakos** [comment]
When you run the [demo](https://github.com/shubham-goel/4D-Humans/blob/244be5a76dbf70f3937e7575de8bbc9c02ae6548/demo.py#L91), check the output of `out['pred_keypoints_3d']`. The names of the joints are listed [here](https://github.com/nkolot/SPIN/blob/2476c436013055be5cb3905e4e4ecfa86966fac3/constants.py#L16) (we return the first 44 of these 49 joints). If you want to estimate the length of a bone, you can estimate the distance between the corresponding joints (e.g., distance of left knee from left ankle).

**Comment by TZYSJTU** [comment]
> When you run the [demo](https://github.com/shubham-goel/4D-Humans/blob/244be5a76dbf70f3937e7575de8bbc9c02ae6548/demo.py#L91), check the output of `out['pred_keypoints_3d']`. The names of the joints are listed [here](https://github.com/nkolot/SPIN/blob/2476c436013055be5cb3905e4e4ecfa86966fac3/constants.py#L16) (we return the first 44 of these 49 joints). If you want to estimate the length of a bone, you can estimate the distance between the corresponding joints (e.g., distance of left knee from left ankle).

Thanks, now I get the pred_keypoints_3d, but I'm not sure how the Coordinate System builds? I mean, the xyz directions in the figure. Could you please show me？
Besides, is the pred_keypoints_3d coodinate normlized?

**Comment by Suleman506** [comment]
Thank you for the great contribution, I have few question.
1. How to convert the "pred_keypoints_3d" to joint angles in world coordinate.
2. Same as previous question from @TZYSJTU, what is the coordinate system of current joints.
3. Is there any other parameter we can utilize to obtain the joint angles such as "predicted smpl parameters" (global orientation & body_pose).
