### ISSUE TITLE
EGL Initialization Failed   for  pyrender.OffscreenRenderer

### ISSUE THREAD

**Issue by m-usamasaleem** [shubham-goel/4D-Humans#110]
![image](https://github.com/shubham-goel/4D-Humans/assets/43682862/2972ba0e-96da-45a9-ad30-0e501a5e5a70)

EGL is failing on Ubuntu 20.

`    self.renderer = pyrender.OffscreenRenderer(viewport_width=self.img_res, viewport_height=self.img_res, point_size=1.0)`

On Ubuntu 20, I encounter an issue with EGL when calling the pyrender.OffscreenRenderer function. This occurs specifically when I attempt to initialize the renderer without a display on an Ubuntu server environment.

**Comment by vvirgooo2** [comment]
Hi, how do you solve this issue, i encounter the same
