### ISSUE TITLE
Evaluation Results for Human 3.6

### ISSUE THREAD

**Issue by m-usamasaleem** [shubham-goel/4D-Humans#111]
Could you clarify how you collected the images used for testing for human3.6 dataset? The image paths seem to only contain information about the subject and the action. How can I access the same images? Could you also explain if there was a specific pattern or method you used to select these images for testing?

I have all the images for testing, I just want to map your image paths to the original human3.6 testing image path pattern.

**Comment by geopavlakos** [comment]
Please check [the h36m scripts here](https://github.com/nkolot/SPIN/tree/master/datasets/preprocess) to see how to map the original Human3.6M data to the format (e.g., naming convention) that we use.
