### ISSUE TITLE
Is it possible to inject a camera position before the solve of the human pose ? 

### ISSUE THREAD

**Issue by hbardak** [shubham-goel/4D-Humans#112]
Hi guys, 

Firstly, amazing work  ! 
I am a VFX artist, that have a bit of coding knowledge. 
in the VFX industry, usually we have already solve with great precision the camera position in the 3D world ( translation, rotation, focal, lens distortion). Would you see a way to pass a solved camera  to human 4D to get a better accuracy for the human poses ? 

At the moment I got : 

![image](https://github.com/shubham-goel/4D-Humans/assets/26234254/b26c43ba-a1c1-4d4d-b68a-dbc963826f2a)

Which obviously doesn't work for me. 

Any ideas how to fix it ?

**Comment by geopavlakos** [comment]
I'm not sure exactly how this visualization was produced, but the first suggestion I have is to use the actual focal length value of the camera (by modifying the [scaled_focal_length](https://github.com/geopavlakos/hamer/blob/2ebe4edae52a88714c5345aa80bfc403a99196ea/demo.py#L143) value of the demo). Please take a look at [this issue](https://github.com/shubham-goel/4D-Humans/issues/16) too. If that looks better for each frame independently, then it should be easy to apply the rotation and translation of each frame to the meshes of the corresponding frame.
