### ISSUE TITLE
How to create .pyd files for my dataset? 

### ISSUE THREAD

**Issue by m-usamasaleem** [shubham-goel/4D-Humans#113]
I've noticed that each image in the shared dataset has corresponding data.pyd file. 

Could you kindly provide the code used to generate these **.pyd files**? I would like to generate these files for my dataset according to your format.

**Comment by wtx9527** [comment]
Hi，I'm having the same issue, have you solved it

**Comment by m-usamasaleem** [comment]
@wtx9527 I prepared this small documentation. I hope it helps you. Making a pickle file is easy but make sure to sort the files while making tar, that's crucial otherwise it won't work. 
https://github.com/m-usamasaleem/annotation_files/blob/main/README.md

**Comment by geopavlakos** [comment]
Thank you, @m-usamasaleem, for this documentation! Would it be ok with you if I share this with a few other users that have similar questions?

**Comment by m-usamasaleem** [comment]
Yes sure.
