### ISSUE TITLE
Issue about dataset used for training HMR2a

### ISSUE THREAD

**Issue by MakingBigNewsWallace** [shubham-goel/4D-Humans#114]
Hi! Great work and amazing results!
I would like to know some details about training HMR2.0a model. Could you please share the dataset weights for training HMR2a? I could only see the mix_all.yaml file for training HMR2.0b. And I also wonder if FILTER_NO_POSES in hmr/configs_hydra/data_filtering is used during training.
Many thanks!

**Comment by geopavlakos** [comment]
For training HMR 2.0a, we adopted the [dataset weights from ProHMR](https://github.com/nkolot/ProHMR/blob/master/prohmr/configs/prohmr.yaml).

We experimented with FILTER_NO_POSES, but we set to False.
