### ISSUE TITLE
Missing output files 

### ISSUE THREAD

**Issue by gokcergun** [shubham-goel/4D-Humans#118]
Hi, I tested your code with some example images. the code runs without an error, but it does not create any output. 

`python demo.py --img_folder example_/bs_data --out_folder example_/bs_out --batch_size=48 --side_view --save_mesh --full_frame`

Terminal Output: 
Lightning automatically upgraded your loaded checkpoint from v1.8.1 to v2.2.0.post0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../.cache/4DHumans/logs/train/multiruns/hmr2/0/checkpoints/epoch=35-step=1000000.ckpt`
WARNING: You are using a SMPL model, with only 10 shape coefficients.
model_final_f05665.pkl: 2.77GB [00:24, 113MB/s]  

After that the code finishes without any error, but also example_/bs_out folder is empty. 
Thanks for your help.

**Comment by geopavlakos** [comment]
Do you get the expected output for the example images of the demo?

**Comment by gokcergun** [comment]
Hi, thanks for your answer. Yes, it works if I run example images

**Comment by geopavlakos** [comment]
Could you list the image names of the images you are trying to use?

**Comment by gokcergun** [comment]
6-7 frames like A_Pose_X_12mm_00777_240208_ZT.000001.60_C.jpg, A_Pose_X_12mm_00777_240208_MH.000005.62_C.jpg,.. 
By the way, the video example worked. The saved outputs are .pkl file from PHALP and a rendered video. Do you have any additional output files, perhaps missing again in my case?

**Comment by geopavlakos** [comment]
Could you pull the latest updates of the code? The image demo was only running on png images. It is updated now.

Regarding running on video, the .pkl file should have all the information you need.

**Comment by gokcergun** [comment]
Great, thanks a lot!
