### ISSUE TITLE
model_config.yaml missing

### ISSUE THREAD

**Issue by ZhenhuiL1n** [shubham-goel/4D-Humans#119]
Hi,

I believe in the hmr2_data.tar.gz zip file, there is a model_config.yaml file missing. Please let me know if I am doing something wrong or where to get the model_config.yaml

Thanks!

**Comment by geopavlakos** [comment]
Can you check again? The yaml files should be there, in the same folder as the `checkpoints` folder.

**Comment by ZhenhuiL1n** [comment]
Yes, I checked

I can not find it even in the zip file, there is only the checkpoint in the checkpoints folder, can you upload it somewhere so that I can download it? Thank you very much!

**Comment by geopavlakos** [comment]
Where did you download the tar file from? I just got it from here: `https://people.eecs.berkeley.edu/~jathushan/projects/4dhumans/hmr2_data.tar.gz` and I can see it as `logs/train/multiruns/hmr2/0/model_config.yaml`.

**Comment by ZhenhuiL1n** [comment]
It was downloaded automatically when I ran the track code . And I found that in my .gz folder, there is no model_config.yaml file for some reason. Now I can get the model_config.yaml by manually downloading the file according to the link you provided. Thank you !!
