### ISSUE TITLE
No OpenGL_accelerate module loaded: No module 

### ISSUE THREAD

**Issue by Sashiyamo** [shubham-goel/4D-Humans#121]
Hi! 

When I try to run the code in Collab, on the line `!python track.py video.source="example_data/videos/gymnasts.mp4" video.start_frame=10 video.end_frame=60`, it gives the error `INFO No OpenGL_accelerate module loaded: No module`. Even if I install OpenGL via `!pip install PyOpenGL-accelerate` the error just changes to `INFO OpenGL_accelerate module loaded`.

I didn't change anything in Collab, just wanted to see how it worked. The only thing I noticed is that Collab asks to restart the environment after `!pip install -e .[all]`. But before, even after restarting the environment, everything worked.

**Comment by geopavlakos** [comment]
You are probably missing the SMPL model in your colab instance. Please download the file `basicModel_neutral_lbs_10_207_0_v1.0.0.pkl` from https://smplify.is.tue.mpg.de/ and put it in your colab environment.

**Comment by maxso-216** [comment]
After testing, I found out the code work when `basicModel_neutral_lbs_10_207_0_v1.0.0.pkl` is put on the root of the directory. Maybe bug in the PHALP?
