### ISSUE TITLE
the effect of running tracking was not good

### ISSUE THREAD

**Issue by Justinitaa** [shubham-goel/4D-Humans#122]
![image](https://github.com/shubham-goel/4D-Humans/assets/155082410/63e6f58b-e221-4fcc-9cd1-df754044e24c)

https://github.com/shubham-goel/4D-Humans/assets/155082410/a5ae5621-0cbf-4473-af11-89ed88fbc89c

The effect of running on the video of gymnasts.mp4 was good, but I changed other videos, such as the video of skating competition and basketball game downloaded from the Internet, the effect of running was not good, and some people in the scene could not be tracked or would be interrupted. How can this be improved?

**Comment by geopavlakos** [comment]
For reliable tracking, we only track people with bounding boxes above a minimum size. This is a hyperparameter you can control and track also people with smaller bounding boxes (i.e., the skaters here), but it might lead to less reliable tracking.
