### ISSUE TITLE
[MISSING FILE] SMPL_NEUTRAL.pkl

### ISSUE THREAD

**Issue by zelingao98** [shubham-goel/4D-Humans#123]
Dear authors,

Thank you for open source this great work!!

I find that `SMPL_NEUTRAL.pkl` is missing in `hmr2_data.tar.gz` where I download from https://people.eecs.berkeley.edu/~jathushan/projects/4dhumans/hmr2_data.tar.gz and unzip it with `tar -xvf hmr2_data.tar.gz`:
<img width="1381" alt="image" src="https://github.com/shubham-goel/4D-Humans/assets/119651008/7a467d44-a36a-447a-ad7e-64a44341aa24">

**Comment by geopavlakos** [comment]
This is intentional because we are not allowed to distribute the SMPL model.
As we describe in the Readme, you will need to download the neutral model from http://smplify.is.tue.mpg.de/.
