### ISSUE TITLE
After testing, I found out the code work when `basicModel_neutral_lbs_10_207_0_v1.0.0.pkl` is put on the root of the directory. Maybe bug in the PHALP?

### ISSUE THREAD

**Issue by Sashiyamo** [shubham-goel/4D-Humans#126]
After testing, I found out the code work when `basicModel_neutral_lbs_10_207_0_v1.0.0.pkl` is put on the root of the directory. Maybe bug in the PHALP?

_Originally posted by @maxso-216 in https://github.com/shubham-goel/4D-Humans/issues/121#issuecomment-2135458151_

**Comment by Sashiyamo** [comment]
After the discussion here https://github.com/shubham-goel/4D-Humans/issues/121 I additionally tried several options to add the model file to the correct directory, but it still doesn't work.

I tried throwing the file directly into the directory, and also via gdown, having uploaded the file to google drive beforehand.

**Comment by geopavlakos** [comment]
If you run the demo on images (`python demo.py ...`) after moving the `basicModel_neutral_lbs_10_207_0_v1.0.0.pkl` file to the `./data/` folder, then you should be good to go.

**Comment by Sashiyamo** [comment]
That's the way it is, if you run it on images, the demo works. The error occurs when processing video.

**Comment by zweiPA** [comment]
i fixed this error， you need to copy the basicModel_neutral_lbs_10_207_0_v1.0.0.pkl file from “./data" folder to /home/{user}/.cache/phalp/3D/models/smpl, and then rename the file "SMPL_NEITRAL.smpl"

**Comment by geopavlakos** [comment]
If you run the `demo.py` first, it should transfer the smpl model in the right location for you to run `track.py` afterwards.
