### ISSUE TITLE
Can't download model checkpoints and data

### ISSUE THREAD

**Issue by GhostLate** [shubham-goel/4D-Humans#127]
Can't download model checkpoints and data by this links: https://people.eecs.berkeley.edu/~jathushan/projects/4dhumans/hmr2_data.tar.gz
https://people.eecs.berkeley.edu/~jathushan/projects/4dhumans/hmr2a_model.tar.gz

**Comment by geopavlakos** [comment]
You should be able to download the data by running `wget <link>`.
