### ISSUE TITLE
[FUNC] cam_crop_to_full

### ISSUE THREAD

**Issue by zelingao98** [shubham-goel/4D-Humans#129]
Thanks for this awesome work!

If I understand correctly, `cam_crop_to_full` is used to get `camera translation`, the code is here:
```python
def cam_crop_to_full(cam_bbox, box_center, box_size, img_size, focal_length=5000.):
    # Convert cam_bbox to full image
    img_w, img_h = img_size[:, 0], img_size[:, 1]
    cx, cy, b = box_center[:, 0], box_center[:, 1], box_size
    w_2, h_2 = img_w / 2., img_h / 2.
    bs = b * cam_bbox[:, 0] + 1e-9
    tz = 2 * focal_length / bs
    tx = (2 * (cx - w_2) / bs) + cam_bbox[:, 1]
    ty = (2 * (cy - h_2) / bs) + cam_bbox[:, 2]
    full_cam = torch.stack([tx, ty, tz], dim=-1)
    return full_cam
```

However, I am confused about `cam_bbox` since it seems like `cam_bbox` consists of `[scale, tx, ty]`.

Could you share some time to teach this operation of function `cam_crop_to_full`, I mean, what is the meaning of `bs`? and why `tz = 2 * focal_length / bs`

Best regards.

**Comment by geopavlakos** [comment]
This function implements equation 1 of [this paper](https://arxiv.org/pdf/2111.07868). Hopefully, this reference is helpful.

**Comment by zelingao98** [comment]
Help a lot. Thank you!!!
