### ISSUE TITLE
PW3D Evaluation with HMR 2.0a

### ISSUE THREAD

**Issue by m-usamasaleem** [shubham-goel/4D-Humans#132]
I am curious about how you evaluated the PW3D dataset using HMR 2.0a. Specifically, on which datasets did you train HMR 2.0a before evaluating it on 3DPW? To clarify, I am referring to HMR 2.0a. 

The paper does not specify which particular datasets were used to train HMR 2.0a for testing on 3DPW. I am referring to Table 1 of paper.
![image](https://github.com/shubham-goel/4D-Humans/assets/43682862/ff970c81-a41f-4024-8111-dc9a08cd634b)

**Comment by geopavlakos** [comment]
We train HMR2.0a on Human3.6M, MPI-INF-3DHP, COCO and MPII. In case, this is not clear from the main paper, this is also clarified in the [Supplementary](https://openaccess.thecvf.com/content/ICCV2023/supplemental/Goel_Humans_in_4D_ICCV_2023_supplemental.pdf).
