### ISSUE TITLE
hmr2_data.tar.gz

### ISSUE THREAD

**Issue by josepedrocruz** [shubham-goel/4D-Humans#133]
https://people.eecs.berkeley.edu/~shubham-goel/projects/4DHumans/hmr2_data.tar.gz this link is not working anymore, can someone post an alternative please?

**Comment by geopavlakos** [comment]
Please check this: https://github.com/shubham-goel/4D-Humans/issues/127#issuecomment-2170618221

**Comment by xiaowenhe** [comment]
@geopavlakos , I use this: https://github.com/shubham-goel/4D-Humans/issues/127#issuecomment-2170618221, still cannot download.  Can give an alternative please? Thank you!
