### ISSUE TITLE
Meaning of keys in .pkl after running track.py

### ISSUE THREAD

**Issue by JerryPW** [shubham-goel/4D-Humans#134]
Hi! Thanks for your great work! 
As I finished running track.py and I got a .pkl file with following ```dict_keys(['time', 'shot', 'frame_path', 'tracked_ids', 'tracked_bbox', 'tid', 'bbox', 'tracked_time', 'appe', 'loca', 'pose', 'center', 'scale', 'size', 'img_path', 'img_name', 'class_name', 'conf', 'annotations', 'smpl', 'camera', 'camera_bbox', '3d_joints', '2d_joints', 'mask', 'extra_data'])```. Some of the keys are easy to understand like 'time', 'frame_path', however, some of the keys are really confused me like 'appe', 'tracked_bbox', 'bbox'... So, I wonder whether it is convenient for you to provide some detailed explanaion about the result after running track.py.

Furthermore, I noticed that some of the people can be detected when I run ```python demo.py``` independently on a single image, but can not be observed when running track.py in a video. Why is that happened? 

Looking forward to your reply soon!

**Comment by geopavlakos** [comment]
The output structure of the PHALP pkl file is described [here](https://github.com/brjathu/PHALP/blob/677074a9bd7acac58c0b98a31b04ae54b93dcd2f/README.md?plain=1#L158).

When you run the `track.py` demo, you use the PHALP tracking algorithm. PHALP has its own set of hyperparameters and the visualization might differ from detection on independent frames. As an example, PHALP might need to track the people in multiple frames and could reject detections on independent frames that cannot initialize a consistent tracklet.

**Comment by JerryPW** [comment]
> The output structure of the PHALP pkl file is described [here](https://github.com/brjathu/PHALP/blob/677074a9bd7acac58c0b98a31b04ae54b93dcd2f/README.md?plain=1#L158).
> 
> When you run the `track.py` demo, you use the PHALP tracking algorithm. PHALP has its own set of hyperparameters and the visualization might differ from detection on independent frames. As an example, PHALP might need to track the people in multiple frames and could reject detections on independent frames that cannot initialize a consistent tracklet.

Thanks for your reply! I'll check it out later for the description. 
Futhermore, your 4D-Humans paper mentioned that the tracker algorithm can be replaced with any other models. However, since the PHALP is installed towards pip, so I wonder how to replace the model in PHALP?

**Comment by geopavlakos** [comment]
Do you want to use HMR2.0 with a different tracking algorithm, or do you want to use PHALP with a different 3D human pose estimation system?

**Comment by JerryPW** [comment]
> Do you want to use HMR2.0 with a different tracking algorithm, or do you want to use PHALP with a different 3D human pose estimation system?

Sorry for missing the reply, my email didn't inform me. 
In your paper section4, you wrote "Originally, PHALP used pose features based on the last layer of the HMR network, i.e., a 2048-dimensional embedding space. This limits the ability of PHALP to be used with different pose models (e.g., HMR 2.0, PARE, PyMAF etc.). To create a more generic version of PHALP, we perform the modification of representing pose in terms of SMPL pose parameters, and we accordingly optimize the PHALP cost function to utilize the new pose distance."
I wonder how your code represent this change, since ```track.py``` directly use the pip installed PHALP from github.

**Comment by geopavlakos** [comment]
The track.py file [defines the method](https://github.com/shubham-goel/4D-Humans/blob/6ec79656a23c33237c724742ca2a0ec00b398b53/track.py#L25) used for Human Mesh Recovery. You could change this with a method other than HMR2.0.
