### ISSUE TITLE
OpenGL issue on Windows while rendering

### ISSUE THREAD

**Issue by 9e0** [shubham-goel/4D-Humans#135]
Hi,

I am facing below, while running the model.
![Screenshot 2023-11-09 153209](https://github.com/user-attachments/assets/76639b6e-7505-4b07-a634-d44fe8953275)

Could you please let me know if I am missing something?

Thanks,
Naveen

**Comment by geopavlakos** [comment]
We don't a windows device to help with this, but you could take a look at other issues (https://github.com/shubham-goel/4D-Humans/issues/12) that discuss running 4D Humans on Windows.
