### ISSUE TITLE
LSP-Extended and PoseTrack Images Link

### ISSUE THREAD

**Issue by m-usamasaleem** [shubham-goel/4D-Humans#136]
Can you please give me links for the following dataset images which are used for evaluation? 

LSP-Extended and PoseTrack

I tried to use following link for PoseTrack but didn't work:

https://posetrack.net/

**Comment by geopavlakos** [comment]
Please check this: https://github.com/shubham-goel/4D-Humans/issues/82#issuecomment-1917857249
