### ISSUE TITLE
I want to change the epoch during training, where should I change it?

### ISSUE THREAD

**Issue by wtx9527** [shubham-goel/4D-Humans#137]
Hi， I modified the epoch in datasets_tar.yaml, but I didn't train on my modified epoch when I trained, or do I need to modify my epoch somewhere else

**Comment by geopavlakos** [comment]
You can edit the number of training iterations [here](https://github.com/shubham-goel/4D-Humans/blob/6ec79656a23c33237c724742ca2a0ec00b398b53/hmr2/configs_hydra/experiment/hmr_vit_transformer.yaml#L7).

**Comment by wtx9527** [comment]
Sorry, I'm stupid, this document doesn't show the epoch, how should I change it, can you elaborate more

**Comment by geopavlakos** [comment]
There is no argument that controls the number of epochs. Instead, you can calculate the number of training iterations (steps) needed for your desired number of epochs and modify [this argument](https://github.com/shubham-goel/4D-Humans/blob/6ec79656a23c33237c724742ca2a0ec00b398b53/hmr2/configs_hydra/experiment/hmr_vit_transformer.yaml#L7) accordingly.

**Comment by wtx9527** [comment]
I have tried several times but still don't understand how to change the epoch with these codes. I hope you can let me know how to modify the code to change the epoch when it's convenient for you. Should I consider the epoch_size parameter in datasets_tar.yaml as well?

**Comment by geopavlakos** [comment]
I'm sorry, there is no argument that controls the number of epochs in the training. You can only control the number of training iterations/steps that the training code will do.
