### ISSUE TITLE
something wrong with hmr2_data.tar.gz

### ISSUE THREAD

**Issue by SuSuYMH** [shubham-goel/4D-Humans#140]
I can not tar it correctly on several OS, leading the lose of "model_config.yaml"!
How can i get this?
Thanks for ur attention!

**Comment by SuSuYMH** [comment]
Oh ! It has nothing to do with the tar and my operation, i can not download the complete zip from "https://people.eecs.berkeley.edu/~jathushan/projects/4dhumans/hmr2a_model.tar.gz"
Would u test the file server plz?

**Comment by SuSuYMH** [comment]
oh,i have fixed the problem, and i am very helpless about China’s National Firewall

**Comment by geopavlakos** [comment]
Please check this issue: https://github.com/shubham-goel/4D-Humans/issues/127#issuecomment-2170618221

**Comment by moonsliu** [comment]
I am wondering how do you solve this problem @SuSuYMH with the China’s National Firewall. Thanks!

**Comment by moonsliu** [comment]
It's indeed the problem of China’s National Firewall. And I have fixed it, thanks!

**Comment by yangchentao-common** [comment]
> It's indeed the problem of China’s National Firewall. And I have fixed it, thanks!
how do you solve this problem? could you share the data with me? 
Thanks！

**Comment by yangchentao-common** [comment]
> > It's indeed the problem of China’s National Firewall. And I have fixed it, thanks!
> > how do you solve this problem? could you share the data with me?
> > Thanks！

https://huggingface.co/camenduru/4D-Humans/tree/d4c3d4b809ba4ce1a780b91d81b151225f48b0d9
