### ISSUE TITLE
On the question of the form of the training set

### ISSUE THREAD

**Issue by wtx9527** [shubham-goel/4D-Humans#142]
Hi,Your training datasets appears to be processed, formatted in '.tar', and contains '.pyd' and '.npz' files, as well as corresponding images. How do I convert a new dataset to something like this, such as 3DPW?

**Comment by zhuoyue725** [comment]
Hello! I've encountered a similar issue with converting the 3DPW dataset into the tar format, and I was wondering if you could kindly share how you managed to resolve it? Thank you in advance for your help.
