### ISSUE TITLE
About the npz file under the hmr2_evaluation_data

### ISSUE THREAD

**Issue by wtx9527** [shubham-goel/4D-Humans#143]
Hello, can you provide the preprocessing code for the evaluation file if it is convenient. That is, how to generate the npz file corresponding to the dataset.

**Comment by geopavlakos** [comment]
Please check how this is implemented in the [SPIN code](https://github.com/nkolot/SPIN/tree/master/datasets/preprocess). For the most part, the procedure is similar.

**Comment by wtx9527** [comment]
Thank you very much for your answer, I would also like to know how the detection.npz file for the training dataset section is obtained, can it be provided
