### ISSUE TITLE
can't download hmr2_data.tar.gz

### ISSUE THREAD

**Issue by SKY-66** [shubham-goel/4D-Humans#145]
Hi,  I could not download data from https://people.eecs.berkeley.edu/~shubham-goel/projects/4DHumans/hmr2_data.tar.gz and it shows 404 file not found.

**Comment by geopavlakos** [comment]
Where did you find that link? This is invalid and I would like to correct it.

**Comment by xiaowenhe** [comment]
> Where did you find that link? This is invalid and I would like to correct it.
The link in hmr2/models/__init__.py L15
Can give a right link?

**Comment by xiaowenhe** [comment]
@geopavlakos ,
The link in hmr2/models/init.py L15
Can give a right link? Thank you!
