### ISSUE TITLE
HMR2.0 with a calibrated camera

### ISSUE THREAD

**Issue by gpastal24** [shubham-goel/4D-Humans#148]
Hello, 

First of all, thank you for making your work public. The results in the wild are top notch so kudos to that. 

I was wondering whether I could use HMR2.0 with a calibrated camera (extrinsics) to obtain 3D joints and meshes within a predefined space.

I think it is straightforward i.e. multiply global_orient with the camera's R matrix and add the camera's T vector to the estimated camera translation. I suppose I would also need to match the coordinate systems by multiplying with a matrix M.

Do you think that's doable?
Thank you :)

**Comment by geopavlakos** [comment]
Yes, it should be easy to do that.
[pred_cam_t_full](https://github.com/shubham-goel/4D-Humans/blob/6ec79656a23c33237c724742ca2a0ec00b398b53/demo.py#L98) gives the translation of the human in the camera frame.
Then you can just apply the additional transformations to move the person in a different coordinate frame.

**Comment by gpastal24** [comment]
Thank you @geopavlakos for the prompt response.
All the best.

**Comment by 2382752230** [comment]
Hi,have you been successful in this attempt? @gpastal24

**Comment by gpastal24** [comment]
> Hi,have you been successful in this attempt? @gpastal24

@2382752230 I didn't find the time yet to try this. I will let you know when I do. If you experiment with this before me, please let me know.

**Comment by gpastal24** [comment]
@2382752230 


I managed to run HMR2.0 with a calibrated camera.

Key things to notice are the following
- Provide the actual camera focal length ( I am not sure if this is really necessary but I like my units to make sense you know)
- Use R, T after calibrating the camera from equation Xc = R*Xw + T. Xw = R.T * (Xc-T). I wasted a couple of hours in this step, trying to find the correct way to make this work. 
- Project the Points back to the original view, or another view assuming a multi camera system.

There is some offset when I project the points to another view, which is to be expected I believe, if you add up the calibration, reprojection and HMR2.0 errors.

**Comment by 2382752230** [comment]
> [@2382752230](https://github.com/2382752230)
> 
> 我设法用校准的相机运行 HMR2.0。
> 
> 需要注意的关键事项如下
> 
> * 提供实际的相机焦距（我不确定这是否真的必要，但我喜欢我的单位有意义，你知道的）
> * 根据公式 Xc = R*Xw + T. Xw = R.T * （Xc-T） 校准相机后，使用 R、T。我在此步骤中浪费了几个小时，试图找到正确的方法来完成这项工作。
> * 将点投影回原始视图，或投影回假设多相机系统的另一个视图。
> 
> 当我将点投影到另一个视图时，会有一些偏移，如果你把校准、重新投影和 HMR2.0 误差加起来，我相信这是意料之中的。

Hi,thank you very much for informing me of this information. Is it convenient for you to provide the code of calibration part? Please contact me (email: 230127092@fzu.edu.cn) if possible. Thanks again for your help.
@gpastal24
