### ISSUE TITLE
How to get SMPL results

### ISSUE THREAD

**Issue by CYF-cuber** [shubham-goel/4D-Humans#153]
A wonderful work!
I run demo.py and I get .obj files. How can i get smpl results? I mean the  pose parameters of [n, 72] and  shape parameters of  [n, 10]. Perhaps I overlooked some variables.

**Comment by geopavlakos** [comment]
The SMPL parameters are stored in the [`out` variable](https://github.com/shubham-goel/4D-Humans/blob/6ec79656a23c33237c724742ca2a0ec00b398b53/demo.py#L91).

**Comment by CYF-cuber** [comment]
thanks!

**Comment by Jatinkalal** [comment]
The pred_smpl shape is (N x 23 x 3 x3 ) where N is the number of frames but can you explain why 3 x 3 for 23 joints?, as far as i know smpl has axis-angle representation for each joint so considering 23 joints it should be (Nx 23 x3).
Thank You.
