### ISSUE TITLE
Possible error with tensor dimension mismatch

### ISSUE THREAD

**Issue by KuroTaiga** [shubham-goel/4D-Humans#155]
Input: a video
my code: 
frame_resized = cv2.resize(frame, (224, 224))
frame_rgb = cv2.cvtColor(frame_resized, cv2.COLOR_BGR2RGB) / 255.0
input_tensor = torch.tensor(frame_rgb.transpose(2, 0, 1), dtype=torch.float32).unsqueeze(0)
batch = {"img": input_tensor}
batch = recursive_to(batch, self.device)
output = self.model(batch)
error I got:
...
"/PoseCompare/FDHumans/hmr2/models/backbones/vit.py", line 327, in forward_features
    x = x + self.pos_embed[:, 1:] + self.pos_embed[:, :1]
RuntimeError: The size of tensor a (140) must match the size of tensor b (192) at non-singleton dimension 1

Did a bit calculation and investigation:
Input size 244,244 should yield 244*244/16/16 = 192 tokens
In file hmr2/model/hmr2.py, line: conditioning_feats = self.backbone(x[:,:,:,32:-32]) , it reduce the size of the x to 224x160, which matches with the 140 tensor size (224*160/16/16)

I'm fairly sure that I shouldn't have to touch the vit.py under the backbones folder to change the forward_features function to be:
pos_embed = self.pos_embed[:, 1:]  # Exclude the classification token
resized_pos_embed = F.interpolate(pos_embed.transpose(1, 2), size=140, mode='linear', align_corners=False)
resized_pos_embed = resized_pos_embed.transpose(1, 2)
x = x + resized_pos_embed + self.pos_embed[:, :1]  # Add back the classification token

But it seems to be the way to get things working.
not sure what I'm missing.
Any comment would be welcomed!

**Comment by geopavlakos** [comment]
The size of the image in the beginning should be 256x256, not 224x224.
You can follow the demo code for the right order of operations.
