### ISSUE TITLE
3D mesh coordinate accuracy?

### ISSUE THREAD

**Issue by Ideal-H** [shubham-goel/4D-Humans#16]
Hello,
Thank you very much for sharing great project!

Using the img (skates.png) provided as an example by the author as an input, 3D mesh data was obtained with the demo.py code.

The generated 3D mesh data was properly overlapped with the original image, and also matched with high accuracy for each person.
![skates_all](https://github.com/shubham-goel/4D-Humans/assets/89431307/509eda6d-f55f-483f-9c8f-aaca47402325)

However, there was a problem when merging or concatenating them into the same 3D space.
<img width="991" alt="capture" src="https://github.com/shubham-goel/4D-Humans/assets/89431307/6dd6257a-10e9-48e8-9723-c69ed7dbe270">

(The code to combine multiple meshes in the same 3D coordinate system is as follows.)

   merged_meshed = all_meshes[0]
   for i in range(1, len(all_meshes)):
       merged_meshed = trimesh.util.concatenate(merged_meshed, all_meshes[i])
   merged_meshed.export(os.path.join(args.out_folder, f'all.obj'))

In my opinion, this problem seems to be caused by poor accuracy on the z-axis.

Are there any parameters (like focal length of camera) that I need to adjust to improve this?

Or should this be recognized as a limitation of this project?

I have one more question, is there any way to make the created obj file like animation?

**Comment by geopavlakos** [comment]
Here, we use a large focal length value (f=5000), which approximates orthographic projection. You could try a smaller value to avoid these extremes you observe now. For example, for f = 250, you can get something more meaningful (although some inaccuracies are still there):

<img width="763" alt="f=250 frontal view" src="https://github.com/shubham-goel/4D-Humans/assets/1571144/6dc1e892-cf3f-4d6c-8528-43cc77286685">
<img width="654" alt="f=250 side view" src="https://github.com/shubham-goel/4D-Humans/assets/1571144/096f5910-6665-4342-ab7e-1e200fc40ca9">

With that being said, it is important to remember that each person is considered independently during the reconstruction phase, so it is more challenging to place multiple people in the same coordinate frame in a way that is globally consistent.

**Comment by strongBrave** [comment]
Could someone please explain the underlying technical reason why reducing the camera's focal length from a very large value (e.g., f=5000), which leads to scattered and unrealistic depth estimations, to a more conventional value (e.g., f=250) results in a significantly more plausible and coherent 3D reconstruction?
