### ISSUE TITLE
Provided checkpoint

### ISSUE THREAD

**Issue by yohanshin** [shubham-goel/4D-Humans#19]
Hi, I wonder whether the checkpoint that we can download through `demo.py` is HMR 2.0a? Or this checkpoint is not corresponding to those tables in the paper? Thanks!

**Comment by shubham-goel** [comment]
Hi @yohanshin, thanks for asking. 

We will release the evaluation point for the checkpoint soon. The released model is close to the HMR2.0b model reported in the paper but performs better based on our observation.

I hope this clarifies any doubts.

**Comment by shubham-goel** [comment]
Hi @yohanshin  We have added evaluation code to the repo, and updated arxiv to reflect numbers from the released checkpoint. 

Closing issue as resolved.

**Comment by yohanshin** [comment]
@shubham-goel 

Thank you for the clarification! In the meantime, the provided checkpoint (I download through demo.py) still seems to be model `b` only (which performs 54.5 PA MPJPE on 3DPW). Am I correct? Is there any way that I can download `HMR 2.0a` instead of `b`?

**Comment by geopavlakos** [comment]
We have just released the `HMR2.0a` checkpoint. You can find it [here](https://people.eecs.berkeley.edu/~jathushan/projects/4dhumans/hmr2a_model.tar.gz).
