### ISSUE TITLE
SMPL pseudo-GT for training

### ISSUE THREAD

**Issue by fabienbaradel** [shubham-goel/4D-Humans#2]
Hi,

Thanks for releasing the code. I am wondering when will you release pseudo-GT for SMPL for AVA, AI Challenger and Instavariety?
Thanks,

**Comment by shubham-goel** [comment]
Hi @fabienbaradel. Thank you for your interest in our work. 

We are working on releasing the training code, and the pseudo-GT fits will be a part of it. 

It will be public very soon, in a few days.

**Comment by fabienbaradel** [comment]
Great news, looking forward this release :)

**Comment by shubham-goel** [comment]
Closed by #10
