### ISSUE TITLE
Clarification for replicating results

### ISSUE THREAD

**Issue by chaitanya100100** [shubham-goel/4D-Humans#20]
Hello,

I am trying to replicate HMR2 results using the provided data and script. I wanted to clarify a couple of doubts. TIA.

1. In `dataset_tars.yaml`, I had to make the following changes to match the dataset folder names. See the commented path (given in the repo) and the corrected uncommented path. Can you confirm this correction?:
```py
INSTA-TRAIN-WMASK:
    TYPE: ImageDataset
    # URLS: hmr2_training_data/dataset_tars/insta-train-vitpose/{000000..001828}.tar
    URLS: hmr2_training_data/dataset_tars/insta-train-vitpose-replicate/{000000..001828}.tar
    epoch_size: 4_000_000
COCO-TRAIN-2014-VITPOSE-REPLICATE-PRUNED12:
    TYPE: ImageDataset
    # URLS: hmr2_training_data/dataset_tars/coco-train-2014-vitpose-replicate-pruned12/{000000..000044}.tar
    URLS: hmr2_training_data/dataset_tars/coco-train-2014-vitpose-pruned/{000000..000044}.tar
    epoch_size: 45_000
```
2. In `insta-train-vitpose-replicate` directory, there are total 3658 tar files but the dataset_tars.yaml mentions only 1829 files. Is it enough to replicate the results mentioned in the paper?

**Comment by shubham-goel** [comment]
Hi @chaitanya100100 , thanks for pointing this out! 

The path names need to be fixed, as you mention. At release, we reduced the number of images per tar, from 2000 -> 1000, which doubled the number of tars. However, we forgot to update `dataset_tars.yaml` to use all 3658 tar files, thanks for catching it. 

Will make this fix.
