### ISSUE TITLE
Pyrender not working

### ISSUE THREAD

**Issue by smandava98** [shubham-goel/4D-Humans#21]
Hi,

I am on a remote server (using a A10 GPU from Lambda Labs). I can't seem to run this repo at all. This line is the issue:

self.renderer = pyrender.OffscreenRenderer(viewport_width=self.img_res,
                                       viewport_height=self.img_res,
                                       point_size=1.0)

This is my full error message:

File "/home/ubuntu/anaconda3/envs/slahmr/lib/python3.10/site-packages/hmr2/models/hmr2.py", line 59, in __init__
    self.mesh_renderer = MeshRenderer(self.cfg, faces=self.smpl.faces)
  File "/home/ubuntu/anaconda3/envs/slahmr/lib/python3.10/site-packages/hmr2/utils/mesh_renderer.py", line 49, in __init__
    self.renderer = pyrender.OffscreenRenderer(viewport_width=self.img_res,
  File "/home/ubuntu/anaconda3/envs/slahmr/lib/python3.10/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/ubuntu/anaconda3/envs/slahmr/lib/python3.10/site-packages/pyrender/offscreen.py", line 137, in _create
    egl_device = egl.get_device_by_index(device_id)
  File "/home/ubuntu/anaconda3/envs/slahmr/lib/python3.10/site-packages/pyrender/platforms/egl.py", line 83, in get_device_by_index
    raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))
ValueError: Invalid device ID (0)

I tried everything from xvfb to restarting my server but nothing seems to work. Is there any way I can get around this?

**Comment by smandava98** [comment]
It seems the issue is with Python 3.10. 
Pyrender doesnt seem to support it

**Comment by geopavlakos** [comment]
I think this is probably fixed now. I reference also this issue: https://github.com/vye16/slahmr/issues/30.
If you have any other suggestion that could be useful for future users that face this issue, please feel free to share.

**Comment by smandava98** [comment]
Yes, for future users:

I downloaded xvfb and ran the following command:
xvfb-run -s "-screen 0 800x600x24" python run_opt.py data=video run_opt=True run_vis=True

I also installed the following libraries:
libegl1-mesa-dev libgl1-mesa-dev

and made sure to point the code to the python 3.10 path not the default python path (conda has issues in cloud GPUs)

**Comment by botaoye** [comment]
> 

Hi, did you make any other changes? I'm having the same problem as you but can't fix it by following your instructions.

**Comment by smandava98** [comment]
Hi @botaoye what does nvidia-smi give you?

**Comment by botaoye** [comment]
> 

Thanks for your reply. I have solved the problem by changing the docker image.

**Comment by FishWoWater** [comment]
Using OSmesa instead of egl as the pyopengl backend could possibly solve this. 
Install osmesa and replace `egl` in `hmr2/utils/mesh_renderer.py` and `hmr2/utils/renderer.py` to `osmesa` 
```
if 'PYOPENGL_PLATFORM' not in os.environ:
    # os.environ['PYOPENGL_PLATFORM'] = 'egl'
    os.environ['PYOPENGL_PLATFORM'] = 'osmesa'
```
Then use a heuristic blending in `demo.py`
```
# input_img_overlay = input_img[:,:,:3] * (1-cam_view[:,:,3:]) + cam_view[:,:,:3] * cam_view[:,:,3:]
input_img_overlay = 0.2 * input_img[..., :3] + 0.8 * cam_view[..., :3]
```

**Comment by LongDan15** [comment]
> 使用 OSmesa 而不是 egl 作为 pyopengl 后端可能会解决这个问题。 安装 osmesa 并替换`egl`和到`hmr2/utils/mesh_renderer.py``hmr2/utils/renderer.py``osmesa`
> 
> ```
> if 'PYOPENGL_PLATFORM' not in os.environ:
>     # os.environ['PYOPENGL_PLATFORM'] = 'egl'
>     os.environ['PYOPENGL_PLATFORM'] = 'osmesa'
> ```
> 
> 然后使用启发式混合`demo.py`
> 
> ```
> # input_img_overlay = input_img[:,:,:3] * (1-cam_view[:,:,3:]) + cam_view[:,:,:3] * cam_view[:,:,3:]
> input_img_overlay = 0.2 * input_img[..., :3] + 0.8 * cam_view[..., :3]
> ```

No work

**Comment by obtuseanglor** [comment]
> if 'PYOPENGL_PLATFORM' not in os.environ:
>     # os.environ['PYOPENGL_PLATFORM'] = 'egl'
>     os.environ['PYOPENGL_PLATFORM'] = 'osmesa'

no work

**Comment by lingbo-yu** [comment]
> > 使用 OSmesa 而不是 egl 作为 pyopengl 后端可能会解决这个问题。 安装 osmesa 并替换`egl`和到`` hmr2/utils/mesh_renderer.py``hmr2/utils/renderer.py``osmesa ``
> > ```
> > if 'PYOPENGL_PLATFORM' not in os.environ:
> >     # os.environ['PYOPENGL_PLATFORM'] = 'egl'
> >     os.environ['PYOPENGL_PLATFORM'] = 'osmesa'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后使用启发式混合`demo.py`
> > ```
> > # input_img_overlay = input_img[:,:,:3] * (1-cam_view[:,:,3:]) + cam_view[:,:,:3] * cam_view[:,:,3:]
> > input_img_overlay = 0.2 * input_img[..., :3] + 0.8 * cam_view[..., :3]
> > ```
> 
> No work

maybe you need install the lib:
`apt install -y libosmesa6-dev`
and use the xvfb run
