### ISSUE TITLE
Creating data.pyd and detection.npz for our own dataset, so we could train the 4D-humans algorithm on our own dataset.

### ISSUE THREAD

**Issue by ChennyDeng** [shubham-goel/4D-Humans#22]
Hi,

Thanks for releasing the code. I would like to train your algorithm on our own dataset. I wonder how should we sort out our dataset in the correct format? In the dataset you provided, for each image, you created a data.pyd file and a detection.npz file. I wonder what are these two files and how do you create them? Thank you for your time and effort in helping us.

**Comment by shubham-goel** [comment]
Hi @ChennyDeng, thanks for asking!

This will become clear once we release the preprocessing code. Till we make that public, hope this explanation helps:

The `.pyd` file contains almost all the info needed for training (as seen [here](https://github.com/shubham-goel/4D-Humans/blob/e237a38ddab15380f960c055571ba1f94f162c05/hmr2/datasets/image_dataset.py#L220-L227) and [here](https://github.com/shubham-goel/4D-Humans/blob/e237a38ddab15380f960c055571ba1f94f162c05/hmr2/datasets/image_dataset.py#L63-L77)). This includes bbox, keypoints, pseudo-gt 3D fits, etc.

The `.npz` file contains the output of the detector, including masks (see [here](https://github.com/shubham-goel/4D-Humans/blob/e237a38ddab15380f960c055571ba1f94f162c05/hmr2/datasets/image_dataset.py#L69)). We bundled it with the tars during dev but its masks are not needed for final training and could be skipped.

**Comment by danielajisafe** [comment]
In the meantime, @shubham-goel please can you explain how to **read** the ```data.pyd``` files? They appear unreadable without using the ```webdataset``` library. Thanks for your help.

**Comment by HeroBaoYX** [comment]
> 你好
> 
> 感谢您发布代码。我想在我们自己的数据集上训练您的算法。我想知道我们应该如何以正确的格式整理我们的数据集？在您提供的数据集中，您为每个图像创建了一个 data.pyd 文件和一个 detection.npz 文件。我想知道这两个文件是什么，您如何创建它们？感谢您花时间和精力帮助我们。

Have you solved this problem now? Looking forward to your reply

**Comment by luoxue-star** [comment]
@ChennyDeng Have you solved this problem? Looking forward to your reply.
