### ISSUE TITLE
It seems a bug about your demo.py 

### ISSUE THREAD

**Issue by spzhuang** [shubham-goel/4D-Humans#24]
When I run your demo.py with the command `python demo.py --img_folder example_data/images --out_folder demo_out --batch_size=48 --side_view --save_mesh --full_frame`, It raise a error: 
```
Traceback (most recent call last):
  File "/home/jianchang/4D-Humans/demo.py", line 143, in <module>
    main()
  File "/home/jianchang/4D-Humans/demo.py", line 138, in main
    input_img_overlay = input_img[:,:,:3] * (1-cam_view[:,:,3:]) + cam_view[:,:,:3] * cam_view[:,:,3:]
ValueError: operands could not be broadcast together with shapes (6016,4016,3) (6016,4016,0) 
```
It is a calculate error about numpy. 
I don't know how to fix it correctly.

**Comment by geopavlakos** [comment]
Based on the error, I believe that the renderer might have not been setup correctly.

You can take a look at this - for example, you can check the value of `os.environ['PYOPENGL_PLATFORM']` when you setup the renderer [here](https://github.com/shubham-goel/4D-Humans/blob/0e58d8c92a69e1d93e0f8f4ad450bb1d543dd0e8/demo.py#L49). Is this value set to `egl`?

Or, if you don't really need the overlay image, you can visualize only the mesh and change L138 to `input_img_overlay = cam_view`.
