### ISSUE TITLE
Unable to download - hmr2_data.tar.gz

### ISSUE THREAD

**Issue by 9e0** [shubham-goel/4D-Humans#25]
Hi,
I am unable to download the file from below link:
https://people.eecs.berkeley.edu/~jathushan/projects/4dhumans/hmr2_data.tar.gz

It is mentioned in 'hmr2/models/__init__.py' at line-15:
https://github.com/shubham-goel/4D-Humans/blob/main/hmr2/models/__init__.py

This error happens while I try to run demo.py, where code tries to download the above file to cache.
python demo.py --img_folder example_data/images --out_folder demo_out --batch_size=48 --side_view --save_mesh --full_frame

Please let me know if I am doing something wrong.

Thanks

**Comment by geopavlakos** [comment]
I tried running the demo on a colab on a new environment and downloading the file worked for me.
It also works if you run `wget https://people.eecs.berkeley.edu/~jathushan/projects/4dhumans/hmr2_data.tar.gz`.
Could you give it another try?

**Comment by 9e0** [comment]
Thanks geopavlakos, wget worked.
