### ISSUE TITLE
How about the inference speed?

### ISSUE THREAD

**Issue by Jerryzhangzhao** [shubham-goel/4D-Humans#27]
Dose anyone know the running speed? including the inference and mesh rendering process.

**Comment by Pokerlishao** [comment]
I run it on a single 4090, for a 43s video (1300 frames), it takes about 12 mins.

**Comment by danielajisafe** [comment]
Thanks @shubham-goel. To follow up,

How about the training speed? Using the same format, with a batch size of 1, on NVIDIA RTX A6000, dataloading takes about 5-7s to yield a batch of 1 sample. Is this expected and the reason why the training takes 7 days on 8 A100 GPUs, or perhaps there is a bottleneck somewhere else? Secondly, what would be the effective reason for choosing ```webdataset``` if training takes this long? Thanks for your clarification.
