### ISSUE TITLE
Download link restricted

### ISSUE THREAD

**Issue by alloystorm** [shubham-goel/4D-Humans#3]
The URL for data download is not accessible. 

https://people.eecs.berkeley.edu/~shubham-goel/projects/4DHumans/

Could you consider uploading the data to somewhere public accessible? Thanks

**Comment by geopavlakos** [comment]
If you follow the instructions here, you should be able to download the file you need:
https://github.com/shubham-goel/4D-Humans/blob/main/fetch_data.sh

**Comment by alloystorm** [comment]
My bad. 
I didn't have wget on my system and tried to download it in Chrome and it didn't work.
