### ISSUE TITLE
Smpl joint order

### ISSUE THREAD

**Issue by carlosedubarreto** [shubham-goel/4D-Humans#32]
Thanks a lot for the amazing code.

Im trying to make it to work in blender, to import the result that is stored in the pkl file.

I was following the infirmation from dmpl about the 23 bones on the character, but after applying it on the smpl fbx, the legs looked alright but the arms and the head were very odd.

Is there any difference from the default order of the SMPL data?

Tha ks a lot for the attention

**Comment by geopavlakos** [comment]
Hi Carlos,

There shouldn't be a difference with respect to the default order of SMPL data. You can check the typical order of joints [here](https://github.com/vchoutas/smplx/blob/566532a4636d9336403073884dbdd9722833d425/smplx/joint_names.py#L244), which has 23 joints + the root (pelvis). The `'global_orient'` corresponds to pelvis, whereas the `'body_pose'` field corresponds to the rotations of the other 23 joints, from `left_hip` to `right_hand`.

Please let us know if you still face any issues.

**Comment by carlosedubarreto** [comment]
Oh great, thanks for that information.
I'm using this data
![image](https://github.com/shubham-goel/4D-Humans/assets/4061130/aa420e7a-c9f9-4ce2-a32d-1832c84e53ed)

From this presentation
https://files.is.tue.mpg.de/black/talks/SMPL-made-simple-FAQs.pdf

And I think the problem might be because I should have used the global_orient as the pelvis data.

thanks a lot!!!

**Comment by carlosedubarreto** [comment]
And that fixed the issue. thanks a lot!!!

showing what I've got
![image](https://github.com/shubham-goel/4D-Humans/assets/4061130/607a8a70-b361-4f8b-9268-667066ed4b4b)

**Comment by carlosedubarreto** [comment]
For other people that tries to import it in blender, you could try this script
[import in blender.zip](https://github.com/shubham-goel/4D-Humans/files/12216998/import.in.blender.zip)


with that script I was able to get this result
https://github.com/shubham-goel/4D-Humans/assets/4061130/3ad47927-d728-47c6-b066-a0ad6d44474f

**Comment by geopavlakos** [comment]
This is very cool!! Thanks a lot for sharing the code and results.

Would you be interested in submitting a pull request so that we can integrate this 4D Humans -> Blender support? Or, we can also do some minor edits and add instructions (e.g., where to get he fbx files) for people to run this on their own.
Alternatively, if you want to host this in a repo of your own, we would be happy to point to this in the Readme.
I think more people would be interested in this functionality. :)

**Comment by carlosedubarreto** [comment]
For now I could do a blend file and add some instructions, since the person can do almost it all using the script panel in blender. I can also make a quick video showing how to import.
Like this would be ok?

**Comment by carlosedubarreto** [comment]
@geopavlakos 
I made a tutorial at: https://youtu.be/WYdO0fOxEWU
and posted a sample code and blend file at: https://www.patreon.com/posts/86992009 

I explain how to load multiple characters and how to fix odd motions
Hope it helps
