### ISSUE TITLE
Accuracy about the foot joint

### ISSUE THREAD

**Issue by Jerryzhangzhao** [shubham-goel/4D-Humans#34]
Hi，thank you for your great work and sharing.
I test the demo code and get great result, but it looks like that the mesh accuracy of foot(actually toe base) is not accuracy as other joints.
I was wondering that is there a diffrent configuration between toe base joint and other joints?

**Comment by geopavlakos** [comment]
We use a 2D keypoint detection model that does not detect feet keypoints. This leads to the slight misalignment for the toe joints, since they don't have reliable ground truth during training.
