### ISSUE TITLE
About the rendering of mesh

### ISSUE THREAD

**Issue by KeepmovingBenLee** [shubham-goel/4D-Humans#35]
Hi, thanks for your wonderful work.

I notice that in your paper, the rendered mesh in white background is shadowed, like this
<img width="294" alt="image" src="https://github.com/shubham-goel/4D-Humans/assets/32378119/6d74c517-a708-4aa1-ad61-a1ec4c4b0060">

I notice the same shadow effect in the figure of PHALP
<img width="1060" alt="image" src="https://github.com/shubham-goel/4D-Humans/assets/32378119/b2ecb73b-d32d-443f-bb89-21281e7ce412">

So I am wondering how the mesh is rendering with the shadow, or it is processed in other software?

Thanks a lot!

**Comment by geopavlakos** [comment]
The shadow effect is added later as post-processing, it's not part of the rendering pipeline.

**Comment by KeepmovingBenLee** [comment]
> The shadow effect is added later as post-processing, it's not part of the rendering pipeline.

Thanks for replying.
