### ISSUE TITLE
How to choose GPU to run

### ISSUE THREAD

**Issue by carlosedubarreto** [shubham-goel/4D-Humans#37]
Hello, is there a way to choose which gpu is going to be used, in case the pc has more than one GPU?

Thanks

**Comment by geopavlakos** [comment]
For linux, you can run `CUDA_VISIBLE_DEVICES=0 python demo.py` to get the first gpu. I believe there is an [equivalent command](https://stackoverflow.com/questions/49735693/what-is-the-equivalent-of-this-linux-command-on-windows-cmd) for windows.

**Comment by carlosedubarreto** [comment]
Thanks. I thinkg its the same, but on windows we use `set CUDA_VISIBLE_DEVICES=0` and then `python demo.py`
