### ISSUE TITLE
About the SupMat

### ISSUE THREAD

**Issue by KeepmovingBenLee** [shubham-goel/4D-Humans#39]
Hi, thanks for your wonderful work!

In the paper you mentioned that some details are in the SupMat, but there is no that part in the arxiv version, so could you provide the SupMat somewhere or update the arxiv version? I know I could find the SupMat on CVF open access later but the proceedings need a long time to prepare right?

Thanks a lot!

**Comment by shubham-goel** [comment]
Hi @KeepmovingBenLee, thank you for your interest in our work and your patience! 

We'll be updating the arxiv version soon, before ICCV, and will include the SupMat in that version.

**Comment by KeepmovingBenLee** [comment]
Thanks for your reply!
