### ISSUE TITLE
About openpose keypoints

### ISSUE THREAD

**Issue by KeepmovingBenLee** [shubham-goel/4D-Humans#40]
Hi, thanks for your wonderful work!

In the paper you mentioned that you get 2D keypoints for unlabelled datasets, are the pseudo 2D labels in openpose format?

I notice that in the code, openpose keypoints and confidence are used, I am wondering that the openpose keypoints are used for all datasets or used for unlabelled datasets.

Thanks a lot.

**Comment by KeepmovingBenLee** [comment]
And I also wonder that how you generate openpose keypoints.

**Comment by geopavlakos** [comment]
We use [ViTPose](https://github.com/ViTAE-Transformer/ViTPose) to generate 2D keypoints. We do this for the AVA, InstaVariety and AI Challenger datasets.

**Comment by KeepmovingBenLee** [comment]
> We use [ViTPose](https://github.com/ViTAE-Transformer/ViTPose) to generate 2D keypoints. We do this for the AVA, InstaVariety and AI Challenger datasets.

I see. So you use ViTPose to generate pseudo lables in openpose format for the above three datasets, while for other datasets you just use ground truth lables (without pseudo lables in openpose format), right?

**Comment by geopavlakos** [comment]
For MPII, COCO and MPI-INF-3DHP, we use pseudo ground truth SMPL parameters generated by SPIN. For H36M, we use ground truth SMPL parameters from MoSh.
