### ISSUE TITLE
About perspective projection

### ISSUE THREAD

**Issue by KeepmovingBenLee** [shubham-goel/4D-Humans#41]
Hi, thanks for your wonderful work!

I am wondering that why the focal_length is divided by the image_size during perspective projection

`pred_keypoints_2d = perspective_projection(pred_keypoints_3d,
                                                   translation=pred_cam_t,
                                                   focal_length=focal_length / self.cfg.MODEL.IMAGE_SIZE)`
Thanks again and look forward to your reply!

**Comment by shubham-goel** [comment]
Hi @KeepmovingBenLee , that's just to map the `pred_keypoints_2d` to `[-0.5,0.5]` instead of `[-IMAGE_SIZE/2, IMAGE_SIZE/2]`.

**Comment by KeepmovingBenLee** [comment]
Thanks for your reply!

**Comment by dengyang11** [comment]
@XiaobenLi00 hi, 我也不太理解这段，能说下么？
