### ISSUE TITLE
Using SMIL instead of SMPL

### ISSUE THREAD

**Issue by IotaCZE** [shubham-goel/4D-Humans#44]
Hi!
I was wondering whether it is possible to somehow easily exchange the SMPL model for SMIL to get better results on infants. I have just tried using the SMIL model (in place of SMPL), but it gives me completely the same results as with SMPL. I guess I am missing something...
Thanks

**Comment by geopavlakos** [comment]
HMR2.0 predicts shape parameters for the SMPL model. The SMIL model has a different shape space, so you will not get something meaningful by just using the parameters from HMR2.0.

**Comment by geopavlakos** [comment]
Yes, that could work, but you need to retrain or finetune on the appropriate data.
