### ISSUE TITLE
about the ./hmr2_training_data

### ISSUE THREAD

**Issue by lsyss-lsyss** [shubham-goel/4D-Humans#46]
Thanks for your excellent work, the download link in this file "https://github.com/shubham-goel/4D-Humans/blob/main/fetch_training_data.sh" can not open, could you please give me the file in ./hmr2_training_data

**Comment by geopavlakos** [comment]
There is a limit to how many times the training data can be downloaded in a particular time frame. If the link doesn't work, it should be only temporarily.
