### ISSUE TITLE
About the comparsion between HMR 2.0 and ROMP

### ISSUE THREAD

**Issue by MinJunKang** [shubham-goel/4D-Humans#48]
Hello, thanks for sharing the astonishing project.

I am interested in applying this method to human NeRF's preprocessing stage.
Usually, the previous methods rely on [ROMP](https://github.com/Arthur151/ROMP) to precompute SMPL parameters for each video frame. If I understand correctly, HMR 2.0 also works with a monocular input and outputs SMPL pose and betas. 
My questions are
1. What is the difference between ROMP and HMR 2.0 in specific? Does the goal be the same?
2. If the task is the same, do you have any quantitative comparison between them? 

Actually, I did a single sample demo with your code and ROMP and it seems that HMR 2.0 does better. However, the second question aims to further understand the reason for this. (maybe just because of the transformer ?)

![그림1](https://github.com/shubham-goel/4D-Humans/assets/29685163/2ed416da-f63d-4d40-8267-3230967646a0)

**Comment by geopavlakos** [comment]
The tasks of HMR2.0 and ROMP are similar in the sense that they return the SMPL parameters for a person from a single input image. One difference is that ROMP specifically focuses on cases with multiple people.

In terms of quantitative comparison, you can compare the results on the 3DPW dataset (Table 1 of [our paper](https://arxiv.org/pdf/2305.20091.pdf) vs Table 3 for the [ROMP paper](https://arxiv.org/pdf/2008.12272.pdf)).

**Comment by MinJunKang** [comment]
Thanks for your answer!
