### ISSUE TITLE
About the mocap dataset and the dataset download link

### ISSUE THREAD

**Issue by KeepmovingBenLee** [shubham-goel/4D-Humans#49]
Hi, @shubham-goel , thanks for your wonderful work and sharing of dataset!
I want to download the mocap dataset for the training of discriminator, and I may not want to download all dataset in one go, so can you tell me which part of the mocap dataset belongs to? Then I can download the responding part instead of whole data. Or I'll also appreciate it if you can provide extra download link for the mocap dataset.
By the way, the dropbox links same to be unvailable for some reasons
<img width="679" alt="image" src="https://github.com/shubham-goel/4D-Humans/assets/32378119/0e575727-fbe0-427f-bb03-9d33eb9020b8">
and this [link](https://help.dropbox.com/share/banned-links) may provide some information.

Thanks again for your contribution!

**Comment by geopavlakos** [comment]
There is a limit to how many times the training data can be downloaded in a particular time frame. If the link doesn't work, it should be only temporarily.
