### ISSUE TITLE
to get this to run on windows

### ISSUE THREAD

**Issue by 21pl** [shubham-goel/4D-Humans#5]
comment out:

if 'PYOPENGL_PLATFORM' not in os.environ:
   os.environ['PYOPENGL_PLATFORM'] = 'egl'

in the following 2 files
hmr2/utils/mesh_renderer.py
hmr2/utils/renderer.py

excellent work by the way!!

**Comment by shubham-goel** [comment]
Thanks, @21pl. We will add these changes to make the repo windows-friendly :)
