### ISSUE TITLE
Limit on # of processed frames

### ISSUE THREAD

**Issue by dexinhuang** [shubham-goel/4D-Humans#51]
I tried uploading a multiple minute video, however I ended up with only a 40 second video back. Is this being capped somewhere? I traced it to this line from PHALP.py, but not sure where the end frame is being declared. 

list_of_frames = list_of_frames if self.cfg.phalp.start_frame==-1 else list_of_frames[self.cfg.phalp.start_frame:self.cfg.phalp.end_frame]

Thanks

**Comment by geopavlakos** [comment]
You can pass this as an argument to `track.py`. For example:
`python track.py video.source=my_video.mp4 video.end_frame=3000`
Currently the `end_frame` value is set to 1300.
