### ISSUE TITLE
Increasing the number of epoch

### ISSUE THREAD

**Issue by Sairam52** [shubham-goel/4D-Humans#53]
Hi, will increasing the number of epochs improve the quality of the motion capture?
If so, how do I change the number of epochs

**Comment by geopavlakos** [comment]
We haven't tried that, so we don't have a good intuition. It's possible that the model could improve if you train for longer.

**Comment by ouusan** [comment]
Hello, do you know how to train longer now? I have the same question: I make some little change to HMR2.0 model and trained it, the training usually stopped in 39 epochs(3-4days), and when i train the HMR2.0 code, it also stopped at 35 epochs(3 days) and they all stopped with loss_step=100,0000), the loss is still decreasing, so I want to ask where should i change in the code to train longer time? Thank you !!
