### ISSUE TITLE
Way to project SMPL params to 2D image without using keypoint detections?

### ISSUE THREAD

**Issue by smandava98** [shubham-goel/4D-Humans#54]
Hi,

Thanks for the great work. I am reading through the code and I was confused on how to project the 3D SMPL parameters to 2D image without using keypoints. It seems you have to run the keypoint detection model to generate bounding boxes to figure out the scale and size in order to project it back on the image but this is not feasible if I have a dataset of purely SMPL parameters. Is it possible to accurately do this without keypoints? I tried using the current projection code but replacing values like size with default values but the projection is way off.

I'd greatly appreciate any help on this. Thank you.

**Comment by geopavlakos** [comment]
In this work, we don't use 2D keypoints, we only use bounding box detections for each person and run HMR2.0 on each bounding box. HMR2.0 also estimates the camera parameters that enable the projection of the SMPL body estimate to the image. In a different setting, where you only have SMPL parameters, this projection is not possible.

**Comment by smandava98** [comment]
Ah, understood. Thanks!
