### ISSUE TITLE
How to get Pose Θ(3D joint locations), Shape β from the pre-trained model?

### ISSUE THREAD

**Issue by kaenkogashi** [shubham-goel/4D-Humans#55]
Thank you for your work.

Currently, I run demo on images with 4DHumans, but the output is mesh (with 6890 vertices).
How can I get Pose Θ(3D joint locations of 24 joints), Shape β (betas) with format below on 4DHumans pre-trained model?
~~~~~~~~~~~~~~~
{
  "pose": [
    -2.0428097248077393,
    0.11024858802556992,
    -2.333742141723633,
    -0.3365379273891449,
    0.011719911359250546,
    0.15597772598266602,
    -0.18535791337490082,
    -0.05565245449542999,
    -0.0701599195599556,
    0.5772491693496704,
    0.032217949628829956,
    -0.024495713412761688,
    0.15936070680618286,
    0.024038009345531464,
    0.015323049388825893,
    0.219781294465065,
    0.010715791955590248,
    0.03143862262368202,
    0.06791213899850845,
    0.015769684687256813,
    -0.026596715673804283,
    0.09402766823768616,
    0.061577245593070984,
    -0.07461484521627426,
    0.03821762278676033,
    -0.07338492572307587,
    0.09183917939662933,
    0.03599092736840248,
    0.027726667001843452,
    -0.03167799487709999,
    -0.08593683689832687,
    0.13839715719223022,
    0.06819991767406464,
    -0.04061942175030708,
    -0.05313720554113388,
    -0.06050587072968483,
    0.33442655205726624,
    0.0762828141450882,
    -0.033081308007240295,
    -0.02586432732641697,
    -0.26066192984580994,
    -0.03644227609038353,
    -0.016138266772031784,
    0.33069372177124023,
    0.03311172500252724,
    0.17657236754894257,
    0.04906424507498741,
    -0.07966049760580063,
    0.022382577881217003,
    -0.633172333240509,
    -0.9721075892448425,
    -0.05635237693786621,
    0.6847463846206665,
    0.6975662112236023,
    0.23132619261741638,
    -1.2001522779464722,
    0.2783845365047455,
    0.20647276937961578,
    1.0782970190048218,
    -0.22080913186073303,
    -0.08577798306941986,
    -0.1102685034275055,
    0.21007774770259857,
    0.030228132382035255,
    0.13235852122306824,
    -0.22589533030986786,
    -0.07216395437717438,
    -0.07743184268474579,
    -0.12528756260871887,
    -0.10984508693218231,
    0.04706919193267822,
    0.13594649732112885
  ],
  "betas": [
    0.13400566577911377,
    -0.12246442586183548,
    0.7548058032989502,
    0.6801249384880066,
    0.16374310851097107,
    0.17321491241455078,
    0.0016920268535614014,
    -0.013438664376735687,
    0.7659109830856323,
    -0.003035418689250946
  ]
}

**Comment by geopavlakos** [comment]
You can check `out['pred_smpl_params']` in [demo.py](https://github.com/shubham-goel/4D-Humans/blob/094aff9ec4114f1d898424beadad76a4007ac982/demo.py#L79). This includes the `global_orient`, `body_pose` and `betas` fields that correspond to the SMPL parameters.

**Comment by AmoghTiwari** [comment]
@kaenkogashi : 
1. There are 23 body joints and 1 root joint. You can find the root joint pose in d['pred_smpl_params']['global_orient'].
2. The provided rotations are in (3x3) rotation matrix format. You'll need to convert that to a (3x1) euler angle representation.
3. Then you can append the root joint and body joint poses to a single array. (I am not sure if the root joint goes at the start or at the end. But as far as I know, it usually goes at the start).

**Comment by kaenkogashi** [comment]
@geopavlakos , @AmoghTiwari 

Thank you very much for your help!

I have one more question. 
After I get  (3x1) euler angle representation, how do I convert them into 3D joint positions (x,y,z) that can be plotted?
Does the 4D-Humans pre-trained model also output 3D joint positions (x,y,z)?

**Comment by AmoghTiwari** [comment]
4D joint positions are already predicted. Just that they are not saved anywhere. 
In the demo.py script, after the line `out = model(batch)` (roughly around line-80). You can dump the variable `out` using joblib or pkl, and then inspect that variable. I had done this on a local fork of mine [here](https://github.com/AmoghTiwari/4D_Humans/blob/main/demo_w_pkl.py). You can use it for reference.

Once you have the variable out saved in a pkl file, just load that pkl file and search for a key named 'kp3d' or 'j3d' (or something similar).

**Comment by kaenkogashi** [comment]
@AmoghTiwari 

Thank you very much for your reply.

I get keys named "pred_keypoints_3d" and "pred_keypoints_2d" below. But the format looks like there are 44 joints? (not 24)
Also the number are decimals. How can I convert these decimals into integer like 3D joint positions (x,y,z)?

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'pred_keypoints_3d': tensor([[[ 0.3246, -0.6181,  0.0810],
         [ 0.1618, -0.6862,  0.0181],
         [ 0.2146, -0.5923, -0.1336],
         [ 0.2971, -0.3519, -0.1694],
         [ 0.4247, -0.2721,  0.0391],
         [ 0.0774, -0.6367,  0.1792],
         [ 0.0061, -0.4214,  0.3127],
         [ 0.2192, -0.2901,  0.3288],
         [-0.0017, -0.2209,  0.0271],
         [ 0.0045, -0.1198, -0.0223],
         [ 0.0334,  0.2675, -0.0160],
         [-0.0213,  0.6650,  0.0361],
         [-0.0314, -0.1442,  0.1070],
         [ 0.0443,  0.1899,  0.2736],
         [ 0.0693,  0.5707,  0.4071],
         [ 0.3519, -0.6624,  0.0482],
         [ 0.3340, -0.6696,  0.1120],
         [ 0.3081, -0.7314, -0.0170],
         [ 0.2684, -0.7477,  0.1247],
         [ 0.2586,  0.5859,  0.4818],
         [ 0.1890,  0.5828,  0.5283],
         [ 0.0170,  0.6154,  0.4075],
         [ 0.1676,  0.7250,  0.0811],
         [ 0.1277,  0.7427,  0.0047],
         [-0.0813,  0.7069,  0.0303],
         [-0.0418,  0.6170,  0.0041],
         [ 0.0313,  0.1997, -0.0197],
         [ 0.0257, -0.2265, -0.1207],
         [-0.0643, -0.2641,  0.1538],
         [ 0.0333,  0.1468,  0.2665],
         [ 0.0384,  0.5413,  0.3958],
         [ 0.4115, -0.3083,  0.0389],
         [ 0.3249, -0.3799, -0.1664],
         [ 0.2080, -0.6213, -0.1072],
         [ 0.0890, -0.6579,  0.1545],
         [ 0.0407, -0.4556,  0.3291],
         [ 0.2188, -0.3143,  0.3285],
         [ 0.1698, -0.6807,  0.0264],
         [ 0.3398, -0.7529,  0.0712],
         [-0.0197, -0.2456,  0.0168],
         [ 0.1465, -0.6357,  0.0224],
         [ 0.0368, -0.4860, -0.0071],
         [ 0.2655, -0.6670,  0.0630],
         [ 0.3523, -0.7691,  0.0686]]], device='cuda:0'), 'pred_vertices': tensor([[[ 0.3709, -0.6959,  0.1323],
         [ 0.3634, -0.6816,  0.1258],
         [ 0.3532, -0.6887,  0.1333],
         ...,
         [ 0.3177, -0.7356, -0.0179],
         [ 0.3202, -0.7351, -0.0172],
         [ 0.3202, -0.7312, -0.0196]]], device='cuda:0'), 'pred_keypoints_2d': tensor([[[ 0.0959, -0.3680],
         [-0.0024, -0.4099],
         [ 0.0296, -0.3547],
         [ 0.0799, -0.2090],
         [ 0.1565, -0.1594],
         [-0.0532, -0.3781],
         [-0.0957, -0.2475],
         [ 0.0320, -0.1688],
         [-0.1013, -0.1285],
         [-0.0976, -0.0674],
         [-0.0802,  0.1671],
         [-0.1131,  0.4070],
         [-0.1189, -0.0819],
         [-0.0729,  0.1190],
         [-0.0576,  0.3461],
         [ 0.1124, -0.3952],
         [ 0.1014, -0.3987],
         [ 0.0862, -0.4377],
         [ 0.0618, -0.4456],
         [ 0.0554,  0.3543],
         [ 0.0138,  0.3520],
         [-0.0889,  0.3728],
         [ 0.0011,  0.4427],
         [-0.0230,  0.4544],
         [-0.1494,  0.4324],
         [-0.1256,  0.3784],
         [-0.0814,  0.1260],
         [-0.0851, -0.1324],
         [-0.1386, -0.1540],
         [-0.0795,  0.0932],
         [-0.0761,  0.3286],
         [ 0.1485, -0.1812],
         [ 0.0968, -0.2259],
         [ 0.0256, -0.3721],
         [-0.0462, -0.3912],
         [-0.0750, -0.2679],
         [ 0.0318, -0.1832],
         [ 0.0025, -0.4064],
         [ 0.1051, -0.4495],
         [-0.1122, -0.1435],
         [-0.0117, -0.3793],
         [-0.0781, -0.2890],
         [ 0.0602, -0.3977],
         [ 0.1126, -0.4593]]], device='cuda:0')}

**Comment by AmoghTiwari** [comment]
@kaenkogashi: The provided decimal values itself are the joint positions. They are supposed to be in floating point values (decimals) right? Why do you want them to be integers? 

I am not sure about the 44 joint thing. I have observed this thing for a few other methods too, but not sure why this is the case. @geopavlakos / @shubham-goel : Could you please clarify this.

**Comment by kaenkogashi** [comment]
@AmoghTiwari 

Thank you very much for your comments.

>Why do you want them to be integers?
For example, in OpenPose key points detection (as same as 'pred_keypoints_2d' value above) of below picture.
As the pixel size of the image is 683*1024, so the detected blue points (Neck) shall be (x,y)=(357,254).
However, the output of 4D-Humans's  'pred_keypoints_2d'  is not integer, but decimals. 
I just wondering if  'pred_keypoints_2d' is not in pixel scale, then how can I visualize the output of 'pred_keypoints_2d' or 'pred_keypoints_3d' ?

![無題](https://github.com/shubham-goel/4D-Humans/assets/42666564/c04339bc-3f1f-4f07-8e26-b6bf0af0d0f6)

**Comment by kaenkogashi** [comment]
@geopavlakos / @shubham-goel 
Thank you for your great work!

Would you tell me the relationship between the mesh (6890 vertices ),  Pose Θ(3D joint locations of 24 joints), Shape β (betas), and 'pred_keypoints_2d' or 'pred_keypoints_3d' ?

In 4d-humans, the model predict  Pose Θ and Shape β in the first, then calculate mesh from  Pose Θ and Shape β?
The model predict 'pred_keypoints_2d' or 'pred_keypoints_3d' in which stages?

**Comment by geopavlakos** [comment]
Regarding the joints, we augment the joints that SMPL outputs with some extra joint/landmark locations that are helpful for training/supervising HMR2.0 (e.g., eyes, ears, etc). For a list of the joints we use, you can check the list [here](https://github.com/nkolot/SPIN/blob/1e7d8ff4cb0705cf04211760c875098da553c1f8/constants.py#L14). We use the first 44 of the 49 joints of that list.

The `pred_keypoints_2d` correspond to the crop that HMR2.0 sees (not to the full image) and they are normalized to `[-0.5, 0.5]`. If you want to convert them such that they correspond to the pixel space of the full image, you need to multiply with the `box_size` and add the `box_center`. In pseudocode:
`pred_keypoints_2d_full = pred_keypoints_2d*box_size+box_center`

Finally, HMR2.0 predicts pose \theta and shape \beta. If you pass these parameters through SMPL, you will get the mesh vertices and 3D joints, `pred_keypoints_3d`. If you project the 3D joints to the image plane through the predicted camera parameters, you get the 2D joints, `pred_keypoints_2d`.

**Comment by kaenkogashi** [comment]
Thank you very much for the reply!

**Comment by xdobetter** [comment]
> @geopavlakos , @AmoghTiwari
> 
> Thank you very much for your help!
> 
> I have one more question. After I get (3x1) euler angle representation, how do I convert them into 3D joint positions (x,y,z) that can be plotted? Does the 4D-Humans pre-trained model also output 3D joint positions (x,y,z)?

Hello everyone, I have one more question， how to convert (3x3) rotation matrix format to (3x1) euler angle representation

**Comment by AmoghTiwari** [comment]
Check this out: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html
Within this, look at the ".as_rot_euler()" function.
You can initialize an object using the "from_matrix()" function. And then  use the "as_euler()" function. 

A rough pseudo code would be something like this:
r = R.from_matrix(<rotn_matrix>)
euler_angles = r.as_euler('xyz')

Pls read the documentation carefully for more details.

**Comment by ZCWzy** [comment]
> Regarding the joints, we augment the joints that SMPL outputs with some extra joint/landmark locations that are helpful for training/supervising HMR2.0 (e.g., eyes, ears, etc). For a list of the joints we use, you can check the list [here](https://github.com/nkolot/SPIN/blob/1e7d8ff4cb0705cf04211760c875098da553c1f8/constants.py#L14). We use the first 44 of the 49 joints of that list.
> 
> The `pred_keypoints_2d` correspond to the crop that HMR2.0 sees (not to the full image) and they are normalized to `[-0.5, 0.5]`. If you want to convert them such that they correspond to the pixel space of the full image, you need to multiply with the `box_size` and add the `box_center`. In pseudocode: `pred_keypoints_2d_full = pred_keypoints_2d*box_size+box_center`
> 
> Finally, HMR2.0 predicts pose \theta and shape \beta. If you pass these parameters through SMPL, you will get the mesh vertices and 3D joints, `pred_keypoints_3d`. If you project the 3D joints to the image plane through the predicted camera parameters, you get the 2D joints, `pred_keypoints_2d`.

Thanks for the guide, when I use the formula you provided `pred_keypoints_2d_full = out['pred_keypoints_2d'] * box_size + box_center` 
Buf I can't get the 3d joints to project correctly to the 2d image.
(Where the white circle is the 2d joint)
![image_with_points](https://github.com/user-attachments/assets/8334e6ec-6b55-43fe-821a-c4b1d6edefbb)

When I use other images, this has the potential to work, but something is wrong with this one

**Comment by Justinitaa** [comment]
@AmoghTiwari @kaenkogashi 
I got a .pkl file by running track.py, and in that file I extracted the 3d_joints, and intercepted some of the information as follows:
3d_joints: [array([[-2.8718486e-01, -7.5166744e-01,  2.2998667e-01],
       [-1.6642219e-01, -6.6351068e-01,  1.0292265e-01],
       [-9.6075758e-03, -6.2545604e-01,  2.0373139e-01],
       [ 1.0279357e-01, -4.2896354e-01,  3.1757167e-01],
       [-6.7978762e-02, -3.5120371e-01,  4.8845506e-01],
       [-2.6760888e-01, -5.3899467e-01, -8.4407069e-03],
       [-2.5292975e-01, -2.8882870e-01, -7.7291429e-02],
       [-4.0486607e-01, -1.5837581e-01,  6.7398876e-02],
       [-1.5314636e-03, -2.1615791e-01,  2.6278008e-02],
       [ 7.4146807e-02, -1.3799396e-01,  5.2112691e-02],
       [ 2.6961237e-01,  1.7003253e-01,  1.7404395e-01],
       [ 4.5271403e-01,  5.0126529e-01,  4.6340257e-02],
       [-4.7355521e-02, -1.1685089e-01, -5.3188279e-03],
       [-2.9106852e-01,  1.1983880e-01,  1.5947574e-01],
       [-2.3855132e-01,  5.0827360e-01,  8.3282381e-02],
       [-2.4569771e-01, -7.9643202e-01,  2.2368461e-01],
       [-2.9768065e-01, -7.8838718e-01,  1.8275031e-01],
       [-1.5319166e-01, -7.9065788e-01,  1.7652753e-01],
       [-2.6787433e-01, -7.7296245e-01,  8.6717866e-02],
       [-3.6278105e-01,  5.8073884e-01,  2.2207400e-01],
       [-3.7149715e-01,  5.8517128e-01,  1.4058727e-01],
       [-1.9863102e-01,  5.4008555e-01,  3.5266701e-02],
       [ 4.3201709e-01,  5.7590663e-01,  2.2899407e-01],
       [ 5.0781614e-01,  5.5226767e-01,  1.9430286e-01],
       [ 4.8288533e-01,  5.2856648e-01, -1.2670055e-02],
       [ 4.5059079e-01,  4.4229305e-01,  3.6990423e-02],
       [ 2.3787317e-01,  1.1562512e-01,  1.6140664e-01],
       [ 1.2874840e-01, -2.7276033e-01,  7.2813749e-02],
       [-1.1671343e-01, -2.1542217e-01, -7.0440099e-02],
       [-2.8482258e-01,  8.8945180e-02,  1.4328843e-01],
       [-2.2954750e-01,  4.7395110e-01,  6.3516118e-02],
       [-7.7342778e-02, -3.7666583e-01,  4.6462077e-01],
       [ 9.1598317e-02, -4.6208042e-01,  3.3960426e-01],
       [-3.8918350e-02, -6.4481968e-01,  1.8522283e-01],
       [-2.5571617e-01, -5.7589465e-01,  4.8243771e-03],
       [-2.9661471e-01, -3.1598577e-01, -7.2813287e-02],
       [-4.0797624e-01, -1.7939991e-01,  6.2734440e-02],
       [-1.7192465e-01, -6.5598309e-01,  1.0553554e-01],
       [-2.2858347e-01, -8.3181155e-01,  1.3771361e-01],
       [ 6.1788335e-03, -2.4410549e-01,  5.6433678e-04],
       [-1.4638546e-01, -6.0630494e-01,  9.5950007e-02],
       [-5.9450842e-02, -4.6149611e-01,  4.3473933e-02],
       [-2.4040745e-01, -7.2623658e-01,  1.6699974e-01],
       [-2.2167268e-01, -8.5226554e-01,  1.3193452e-01],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00]], dtype=float32),
There are 45 lines in total.My understanding is that this is information about the joints of a person detected in that frame, and how he corresponds to each of the 44 joints, for example, which joints correspond to the first row, do you understand that part of the information?
