### ISSUE TITLE
bvh exporting

### ISSUE THREAD

**Issue by kotaxyz** [shubham-goel/4D-Humans#6]
first of all the demos looks awesome ,thanks for your awesome work, are you planning to add a functionality for exporting bvh data

**Comment by shubham-goel** [comment]
Hi @kotaxyz. Thank you for your interest in our work. Unfortunately, we don't plan on releasing a `.bvh` export ourselves. 

I found this [smpl2bvh](https://github.com/KosukeFukazawa/smpl2bvh) repository though, you might find it helpful.
