### ISSUE TITLE
Shape predictions

### ISSUE THREAD

**Issue by smandava98** [shubham-goel/4D-Humans#60]
Hi. Why is shape being predicted? I thought for a neutral model, the shape is the same across all the images?

**Comment by geopavlakos** [comment]
The neutral model means that the shape is not gender-specific. You can still capture specific body shape types by predicting the right body shape parameters. We refer to the [SMPL paper](https://files.is.tue.mpg.de/black/papers/SMPL2015.pdf) for this.
