### ISSUE TITLE
Annotate video with and extract keypoints instead of mesh

### ISSUE THREAD

**Issue by adelaneh** [shubham-goel/4D-Humans#62]
Hi,

    Is it possible to export the keypoints from a video in `track.py` instead of mesh?

Thanks,
-Adel

**Comment by geopavlakos** [comment]
You can readout the 3D keypoints directly from our output.

If you are using the tracking functionality `track.py`, these are stored as part of the output pkl file, e.g., `your_output_pkl['your_frame_name']['3d_joints']`.

If you are using the single frame functionality `demo.py`, you can read them from the `out` variable [here](https://github.com/shubham-goel/4D-Humans/blob/bb0b0d0a95852b3d362528c278e0d443232ce743/demo.py#L76), e.g., `out['pred_keypoints_3d']`.

**Comment by adelaneh** [comment]
Thanks a lot, @geopavlakos
