### ISSUE TITLE
Multi gpu training

### ISSUE THREAD

**Issue by siekny** [shubham-goel/4D-Humans#66]
Hi, thanks for your excellent work!
How can I train on multi-gpu?
I am trying to run on multi-GPU using python train.py -m but I got the error:
Error stream produced:

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
usage: _submit.py [-h] folder
_submit.py: error: unrecognized arguments: hydra.run.dir="...." hydra.job.name=train_ddp_process_1

**Comment by geopavlakos** [comment]
You can use the command in the Readme, and add some additional options for more control. For example, you can run on 4 GPUs, by running:
`python train.py exp_name=hmr2 data=mix_all experiment=hmr_vit_transformer trainer=gpu launcher=local trainer=ddp trainer.devices=4`
