### ISSUE TITLE
Visualization of the reconstructed human mesh

### ISSUE THREAD

**Issue by KeepmovingBenLee** [shubham-goel/4D-Humans#67]
I wonder that the configuration of the parameters (e.g. color, material and camera) used for rendering mesh using pyrender. And I notice that the transfomation for side view is in the code, but how about the top view?

Thanks a lot for your work and look forward to your reply.

**Comment by geopavlakos** [comment]
We just added support for rendering the top view. Please check the updated demo.

**Comment by KeepmovingBenLee** [comment]
> We just added support for rendering the top view. Please check the updated demo.

Thanks a lot!
