### ISSUE TITLE
Unable to download hmr2_data.tar.gz 

### ISSUE THREAD

**Issue by zweiPA** [shubham-goel/4D-Humans#68]
this link https://people.eecs.berkeley.edu/~jathushan/projects/4dhumans/hmr2_data.tar.gz is not found

**Comment by geopavlakos** [comment]
The link is working for me. Could you please check again?

**Comment by KeepmovingBenLee** [comment]
> this link https://people.eecs.berkeley.edu/~jathushan/projects/4dhumans/hmr2_data.tar.gz is not found

You can try to download by using wget instead of opening the link directly.
