### ISSUE TITLE
A colab error about tracking

### ISSUE THREAD

**Issue by spzhuang** [shubham-goel/4D-Humans#69]
I run your colab ipynb. The part of tracking existing a error:
![image](https://github.com/shubham-goel/4D-Humans/assets/35912166/b8e338fb-88f0-4d35-a31c-2e126dc0a146)
I just running your ipynb step by step.
Please give me a hand .

**Comment by geopavlakos** [comment]
We have fixed an issue with colab and it should be working now. Could you please try again?

**Comment by spzhuang** [comment]
It work ! 
Amazing!
![image](https://github.com/shubham-goel/4D-Humans/assets/35912166/912a08cf-8a2f-48ac-a648-dab251bf902e)
