### ISSUE TITLE
about the training data，do you use EFT fits or what?

### ISSUE THREAD

**Issue by ShamLich** [shubham-goel/4D-Humans#73]

**Comment by geopavlakos** [comment]
For Human3.6M, COCO, MPII and MPI-INF-3DHP, we use the existing [SPIN](https://github.com/nkolot/SPIN) fits. For AVA, InstaVariety and AI Challenger, we introduce fits done with [ProHMR](https://github.com/nkolot/ProHMR).

**Comment by geopavlakos** [comment]
I'm sorry for the confusion, I wanted to say that for these datasets we use the same (pseudo) ground truth as SPIN. This means that for COCO, MPII and MPI-INF-3DHP we use the SPIN fits, but for Human3.6M, we use the MoSh fits, the same way that SPIN did.

With that being said, how do you get the values for the "spin fits for Human3.6M". SPIN does not release such fits.

**Comment by geopavlakos** [comment]
Is it possible that these fits were released from some other work instead and they were labelled as "SPIN fits"?
In either case, if these fits are generated the SPIN way (with in the loop optimization), it is expected to be different from the MoSh fits that HMR2.0 and SPIN use for training.

**Comment by ShamLich** [comment]
> Is it possible that these fits were released from some other work instead and they were labelled as "SPIN fits"? In either case, if these fits are generated the SPIN way (with in the loop optimization), it is expected to be different from the MoSh fits that HMR2.0 and SPIN use for training.

You might be right, I can't quite remember either， maybe i get it from other work
