### ISSUE TITLE
how about using smpl 49 keypoints(like spin did) instead of your smpl 44 keypoints? will the result be worse?

### ISSUE THREAD

**Issue by ShamLich** [shubham-goel/4D-Humans#74]

**Comment by geopavlakos** [comment]
This shouldn't make a difference. There is redundancy in the [49 keypoints defined by SPIN](https://github.com/nkolot/SPIN/blob/1e7d8ff4cb0705cf04211760c875098da553c1f8/constants.py#L14), i.e., the five face keypoints appear twice. By using 44 keypoints, we just ignore one of the two appearances of the five face keypoints.

**Comment by ShamLich** [comment]
> This shouldn't make a difference. There is redundancy in the [49 keypoints defined by SPIN](https://github.com/nkolot/SPIN/blob/1e7d8ff4cb0705cf04211760c875098da553c1f8/constants.py#L14), i.e., the five face keypoints appear twice. By using 44 keypoints, we just ignore one of the two appearances of the five face keypoints.

BIG Thanks for your quick help！
