### ISSUE TITLE
Is it easy to train this work with 4 V100 24G or 8 3090 24G? (no A100)

### ISSUE THREAD

**Issue by ouusan** [shubham-goel/4D-Humans#75]
Thank you for your work, It's so cool !
you mentioned that you used 8 A100s for training, did you use 40G or 80G?Could you please give me some advices that If I use 4 V100 24G or 8  3090 24G, can we train this work in two weeks? And in your opinion, which is better? Looking forward to your reply。 Thankyou！！

**Comment by geopavlakos** [comment]
We haven't experimented with these setups, so we cannot predict with certainty. They could be sufficient with some trade-off (e.g., maybe require training for longer, or return slightly worse results).
