### ISSUE TITLE
Is there any specific reason for choosing Detectron2 as human detection model?

### ISSUE THREAD

**Issue by Ideal-H** [shubham-goel/4D-Humans#77]
Actually, we have some questions for your work.

The question is :

Is there any specific reason you chose the ViTDet(or detectron2) for a human detection model?

As our knowledge, there are more faster models like YoloV7.
These model can be operated for more than 15~30 fps with good accuracy.
So, we wonder why you chose detectron2(like accuracy or something).

 we would like to say thanks again for your great study of 3D human reconstruction.
And, please share your research experience.

Thank you.
Best regard. :)

**Comment by geopavlakos** [comment]
We used ViTDet for the demo because of its high accuracy. Since we only need a bounding box as input, any other human bounding box detection system would be sufficient for this task. You can modify the demo and experiment with it.
