### ISSUE TITLE
use SMPLX model with hands and feet?

### ISSUE THREAD

**Issue by cga-cmu** [shubham-goel/4D-Humans#80]
I get the message 
WARNING: You are using a SMPL model, with only 10 shape coefficients.

How do I use a more complex model such as SMPL-X, which does a better job on hands and feet?

Thanks
Chris Atkeson

**Comment by geopavlakos** [comment]
Our approach only estimates the body pose parameters from a single image, so even if a more expressive model is used, we would not be capable to directly estimate the hand pose parameters out of the box. For modeling the hands together with the body, other methods like [SMPLify-X](https://github.com/vchoutas/smplify-x) or [ExPose](https://github.com/vchoutas/expose) would be more suitable (although you would lose some accuracy and robustness overall, compared to using 4D Humans). There is also work that models that hands independently, e.g., our recent [HaMeR](https://github.com/geopavlakos/hamer) approach.

**Comment by ireneMsm2020** [comment]
@geopavlakos  Can the hand data reconstructed by the HaMeR method fit seamlessly with this method 4d-Humans?
