### ISSUE TITLE
Training data preprocessing

### ISSUE THREAD

**Issue by xiaoyudanaa** [shubham-goel/4D-Humans#84]
Dear Author, I have read HMR 2.0 and I am very excited by the results. I would like to create something based on your article, but I don't know much about dataset preprocessing, so I'd like to ask you about it: how should I make a new dataset in the form of the tar balls that you originally used in your code? Looking forward to your reply.

**Comment by wtx9527** [comment]
Hi，I'm having the same issue, have you solved it

**Comment by geopavlakos** [comment]
This documentation from a fellow user could be helpful: https://github.com/m-usamasaleem/annotation_files/blob/main/README.md
