### ISSUE TITLE
I got this image after training ,what does the last row mean? Thankyou!!!

### ISSUE THREAD

**Issue by ouusan** [shubham-goel/4D-Humans#86]
Hello!   I got the following picture after training, i can understand from the second to the fourth row, they are reconstruction result, side view, 2D key point prediction, right? but I'm a little confused what does the last row represent please? Looking forward to your reply!!!
![比较3](https://github.com/shubham-goel/4D-Humans/assets/106128352/636b72e7-f599-4c40-8644-c6c43ccf0fb4)

**Comment by geopavlakos** [comment]
The last column visualizes the annotated keypoints. Here some keypoints have not been annotated, that's why they are missing.
