### ISSUE TITLE
camera global coordinates

### ISSUE THREAD

**Issue by FrankBu0616** [shubham-goel/4D-Humans#89]
Hi, thank you for the amazing work!
Is there an easy way to get camera location information in global coordinates?

**Comment by geopavlakos** [comment]
The [pred_cam](https://github.com/shubham-goel/4D-Humans/blob/124e8b2dc041fdd7e02f879ce851952cb810636b/demo.py#L89) variable returns the translation of the person for a camera capturing the local bounding box.
The [pred_cam_t_full](https://github.com/shubham-goel/4D-Humans/blob/124e8b2dc041fdd7e02f879ce851952cb810636b/demo.py#L94) variable returns the translation of the person for a camera capturing the whole image.
In both cases, we assume that the camera is at (0,0,0).

If I understand correctly, the `pred_cam_t_full` translation is what you need?
