### ISSUE TITLE
2d keypoints

### ISSUE THREAD

**Issue by viqsoul** [shubham-goel/4D-Humans#90]
I want to use the confidence of 2d keypoints information.I read through the code, it seems that the 2d keypoints (not projected from 3d keypoints)is not used in the project, right?

**Comment by geopavlakos** [comment]
We do not predict 2D keypoints, we only predict the 3D shape. The 2D keypoints can be estimated as the reprojection of the 3D keypoints of the shape, so there is no confidence value associated with them.
