### ISSUE TITLE
How to improve estimation of arm and hand angles in extreme scenarios?

### ISSUE THREAD

**Issue by mrEuler** [shubham-goel/4D-Humans#93]
As I already checked many repos and papers, that work with SMPL fitting, I didn't get good apropriate result in hand/arm/forearm tracking in negative extreme angles. Here are few screenshots (left -- 4d humans, middle and right WHAM w/o and w postprocessing). Is there any way how to improve this or finetune the model?
Overall 4d humans have generally best results IMHO, except these issues with extreme angles during f.e. tennis serve:
![Screenshot 2024-02-08 144628](https://github.com/shubham-goel/4D-Humans/assets/50824526/56475ae1-484f-46b6-b549-6253e8562905)
![Screenshot 2024-02-08 144502](https://github.com/shubham-goel/4D-Humans/assets/50824526/68815bfa-3d18-4705-a95a-dee0157e542d)
![Screenshot 2024-02-08 144516](https://github.com/shubham-goel/4D-Humans/assets/50824526/7e752bd8-d65c-45c3-9097-e7188fb2a518)
![Screenshot 2024-02-08 144541](https://github.com/shubham-goel/4D-Humans/assets/50824526/3ee69d4d-bbcb-4309-b8c1-7beba69e6750)

**Comment by geopavlakos** [comment]
If you want to potentially refine the output from 4D Humans, you could use our [slahmr](https://github.com/vye16/slahmr) work, which adds some overhead in the runtime but it typically leads to more precise results.

Could you also share the original RGB video you are using for this inference?

**Comment by mrEuler** [comment]
@geopavlakos thank you! Btw I just found [slahmr](https://github.com/vye16/slahmr) 30 mins ago. So will try and let you know how it'll work!
Here is the RGB video: https://drive.google.com/file/d/11I6hfR0BkOGnqS1wc0hnQAngtTZsQTEM/view?usp=sharing

**Comment by mrEuler** [comment]
@geopavlakos I also would say not to refine result itself, but to refine model with additional dataset, that can be captured and transformed to SMPL type.

**Comment by geopavlakos** [comment]
In terms of finetuning the model, that is definitely possible, if you have this type of data (i.e., images and corresponding 3D ground truth in SMPL format). We have not tested finetuning HMR2.0 with data from a specific activity, but I expect it would help reconstructing poses from that particular activity more accurately.
