### ISSUE TITLE
How can i train longer? it seems the loss is still decreasing but the training stopped only in 39 epochs(3-4days) with loss-step=100,0000

### ISSUE THREAD

**Issue by ouusan** [shubham-goel/4D-Humans#97]
Hello, Thank you for your work!! I have a question: I make some little change to HMR2.0 model and trained it, the training usually stopped in 39 epochs(3-4days), and when i train the HMR2.0 code, it also stopped at 35 epochs(3 days) and they all stopped with loss_step=100,0000. the loss is still decreasing, so I want to ask where should i change in the code to train longer time? Thank you !!! (in configs/__init__.py , it seems the default epoch is 100, I don't know if i have an early stop.... )

**Comment by geopavlakos** [comment]
You can control the number of iterations in this file:
`hmr2/configs_hydra/experiment/hmr_vit_transformer.yaml`
through the TOTAL_STEPS in GENERAL.
