### ISSUE TITLE
WARNING: You are using a SMPL model, with only 10 shape coefficients.

### ISSUE THREAD

**Issue by jim-1ee** [shubham-goel/4D-Humans#99]
when i run "python demo.py  --img_folder example_data/images  --out_folder demo_out  --batch_size=48 --side_view --save_mesh --full_frame" ,return WARNING: You are using a SMPL model, with only 10 shape coefficients.how to resolve it?

**Comment by geopavlakos** [comment]
This is just a warning from the [smplx package](https://github.com/vchoutas/smplx). It doesn't affect you negatively. It's more of a reminder of the number of the shape coefficients you are using.

**Comment by jim-1ee** [comment]
> This is just a warning from the [smplx package](https://github.com/vchoutas/smplx). It doesn't affect you negatively. It's more of a reminder of the number of the shape coefficients you are using.

但是程序会终止。我尝试了好几个版本的SMPL都还会报这个错，应该要怎么修改代码呢？

**Comment by geopavlakos** [comment]
Are you sure there is no other error message? It's unlikely that smplx is the problem. Maybe the environment installation was not performed correctly?
If you don't know where the error happens, one way to debug this is to include a breakpoint (`import ipdb; ipdb.set_trace()`) in the `main` function and run the code step by step until you see which commands creates the problem.
